### ISSUE TITLE
Kafka+SQL global and artifact rules deletion approach

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#1073]
Currently when deleting **all** global or artifact rules, we are sending one Kafka message per rule (due to our log compaction approach).  For example:

https://github.com/Apicurio/apicurio-registry/blob/master/storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlRegistryStorage.java#L624-L635

This is perhaps the best we can do if we want to continue using per-rule log compaction.  However, I'm adding this issue to see if anyone has a better idea. :)

Ping @Apicurio/developers

**Comment by carlesarnal** [comment]
For the global rules the only idea that I have in mind is to store them in a separated topic and just throw away that topic info. I don't have a valid idea for the artifact rules.

**Comment by famartinrh** [comment]
One idea would be to have all global rules in a big message to hold the configuration of all global rules. But because of transactionality and message size this solution is not ideal.

Another idea would be to have a garbage collector process that will send NULL messages to remove all the messages related to a global rule after the rule being deleted, it's probably safer to delay the execution of the garbage collection process insted of triggering it inmediatly after receiving the request to delete a global rule (or all global rules)...

So probably the most ideal solution is what we currently have. We could implement some garbage collection process in the future  but it's not urgent at all. I don't expect the amount of kafka messages for global rules to be an issue.

**Comment by EricWittmann** [comment]
I agree that this is probably not much of an issue, for the reasons you indicate.  Rule configuration changes (both global and per-artifact) will likely be rare.  And using the "delete all" functionality in our API to remove all rules at once will be even *more* rare.  I do wonder though if there might be a way to batch multiple Kafka messages together to ensure they are delivered (or not) together.  The risk with the current approach is that a subset of rules are deleted because we're sending the "delete validation rule" message and then the "delete compatibility rule" message a little later.  If the node crashes in between, the first could be sent without the second.  But if there were a way for a Kafka producer to send both messages together, that would be ideal.

Any volunteers to look into that?  :)

**Comment by carlesarnal** [comment]
I do know that the concept of transactions exists in Kafka but I'll need to dig a bit more into the details. I can volunteer for this one.

**Comment by EricWittmann** [comment]
OK great, thanks @carlesarnal

**Comment by EricWittmann** [comment]
I've been thinking more about this, and I think the current semantics are OK for this.  While it is possible for a producer to crash in between sending of deletes, I think this is a very low probability (and also low stakes) occurrence.

To mitigate this somewhat I am setting `linger.ms` in the Kafka producer to a default of `10ms` - this will result in the producer batching the messages for higher throughput (but introducing a 10ms latency).  It should also result in the multiple "delete rule" messages being sent as a batch.  Therefore the odds of sending only a subset of those delete messages should be very small.

**Comment by EricWittmann** [comment]
Note:  I think the Kafka transaction API is overkill for this.

**Comment by alesj** [comment]
> Note: I think the Kafka transaction API is overkill for this.

Good note.
Kafka tx makes things pretty slow - when dealing with lots of msgs.
Use it if you really really need it.
