### ISSUE TITLE
Does it have a go-client?

### ISSUE THREAD

**Issue by alok87** [Apicurio/apicurio-registry#1091]
Do we have a go-client to talk to apicurio-registry? Also does it support AVRO storage in kafka?

**Comment by EricWittmann** [comment]
We have a REST API you can use and a Java client, but we don't currently have a Go client.  However, we do have support for the Confluent Schema Registry API (in addition to our own API), so if there is a Go client for that you could try it.

**Comment by EricWittmann** [comment]
I'm not sure what you mean by supporting Avro storage in Kafka.  We certainly support Avro schemas stored as artifacts in the registry.  But if you are asking whether we use Avro to encode data when we use Kafka as our storage mechanism, then no - we're using Protobuf in the Streams storage implementation and JSON (currently) in the new Kafka+SQL storage implementation.

**Comment by alok87** [comment]
Thank you for the detailed answers.

In one of the projects we wanted to support both confluent schema registry and apicurio schema registry.  I was building an adapter to support both. 

1. Here is the go client for confluent schema registry https://github.com/confluentinc/schema-registry will this work for apicurio as well?  
2. Also does moving to apicurio in Debezium from confluent schema registry is as straightforward as change the schema registry URL?

**Comment by EricWittmann** [comment]
I have not personally tested either of these myself, so ymmv.

1. Because we have also implemented Confluent's schema registry API, that go client should work as long as you give it the right URL.  We do not currently have plans to create our own go client, but anything is possible!
2. I assume this should work, but I also assume that Debezium can be configured to use Apicurio Serdes classes instead of the Confluent ones.  Maybe @jpechane or @gunnarmorling could comment on this??

By the way, the Apicurio Registry API URL is this:

https://host:port/api

But if you want to use a Confluent client of some kind (e.g. the Go client) then you need to use this:

https://host:port/api/ccompat

**Comment by gunnarmorling** [comment]
Ad 2., yes, that migration should be as straight-forward as that if you use the ccompat API. If you want to use Apicurio's own API, you'd have to use the Apicurio Connect converters instead of Confluent's. The required steps are described [here](https://debezium.io/documentation/reference/configuration/avro.html). If you use Debezium's container image for Kafka Connect, they come with the Apicurio converters baked in already. Also look [here](https://github.com/debezium/debezium-examples/tree/master/tutorial#avro-format-using-apicurio-avro-converter) for a comprehensive example.

**Comment by alok87** [comment]
Thank you, that answers all the questions. :)
