### ISSUE TITLE
Provide an in-memory Registry Service for Tests

### ISSUE THREAD

**Issue by tomasAlabes** [Apicurio/apicurio-registry#1153]
Hi, Confluent has its own [MockSchemaRegistry](https://github.com/confluentinc/schema-registry/blob/master/client/src/main/java/io/confluent/kafka/schemaregistry/testutil/MockSchemaRegistry.java) that can be used for testing. It'd be super useful for Apicurio to have one.
We are using a very simple (and incomplete) one like [this](https://gist.github.com/tomasAlabes/7f2e6d43fc88eac447f5bdbd9feab389).

Thanks!

**Comment by EricWittmann** [comment]
I'm wondering though  - are you looking for a mock version or something that is fully functional but runs in-memory.  The latter we already have (though perhaps not as easy to use as you may need).  In my view, a mock version is something that would return specific configured responses, while an in-memory version is just the full application but persisting data in memory.

**Comment by EricWittmann** [comment]
For example, you could use docker integration in your tests to run this:

https://hub.docker.com/r/apicurio/apicurio-registry-mem

That is the in-memory version of the registry.

If you cannot or don't want to use docker, the in-memory version of Apicurio Registry could still be used, but we might need to think a bit about how best to start/stop it.

**Comment by tomasAlabes** [comment]
Hi @EricWittmann, thanks for answering. In my case I use the mock registry (which is functional) in the context of tests using Spring Kafka's `@EmbeddedKafka`. This way you avoid spinning up any other real service.
If you check our half-baked implementation is just some maps with the stuff. It doesn't need to be a server per se.

**Comment by EricWittmann** [comment]
Oh I see - I am just now realizing that what you did is mock the **client** not the Registry server.  That's interesting.  I didn't catch that before.

So can you quickly describe one of your tests?  I'm guessing what you're doing is testing a Kafka application by firing up an embedded Kafka instance, and configuring the Kafka app's Serdes to somehow use the mock registry client instead of the real client.  That way no registry server is needed.  Is your consumer application then registering the schema(s) in the mock registry client so that your consumer app (which I assume shares the same mocked client) can pull them out?  Did I get that somewhat right?

The trouble with any sort of **functional** mock of the registry is that it's non-trivial to implement it in a way that is 1-1 conformant with the actual registry server.  The server does all sorts of interesting things like extracting meta-data, validating content, etc.  If we did this, I think we would need to constrain the scope so that it wasn't a nightmare to maintain.

@Apicurio/developers Any thoughts on the idea of providing a mock registry REST client for use in testing Kafka apps?

**Comment by alesj** [comment]
> it wasn't a nightmare to maintain

That was my first thought ...

Where otoh, running simple in-memory registry is trivial.
And if we generate native build for it, it's even easier (and faster boot).

But any community contribution is always welcome.
Where in this case it would probably be in some sort of sandbox scope / state?

**Comment by tomasAlabes** [comment]
@EricWittmann your example was spot on.
I'd say that the mock client can cover at least the most common flows, then devs can spy the mock client if they want to change a particular behavior.
@alesj I'm not sure what you mean by the native in-mem registry but it's very beneficial not having to boot any other server to run the tests. At least that's how the `@EmbeddedKafka` + Confluent's Mock Registry works.

**Comment by EricWittmann** [comment]
But I assume that `@EmbeddedKafka` starts up a Kafka server, right?  It might be easier to provide (and maintain) a `@EmbeddedApicurioRegistry` than a mock version of the client.

Although I do agree that it might be easy enough to have a client that just supported the most common flows.  We'd have to think a little bit about what those flows would be.  I guess at a minimum it would be all flows found in the Apicurio Registry serdes classes.  Perhaps that defines the scope.  So you could use **our** Serdes classes in your tests, with our mock registry client, and everything should work.  And we could ensure that the mock client works for those flows by doubling up all our existing serdes unit tests so they run against the real REST client and the mock REST client.

**Comment by alesj** [comment]
> It might be easier to provide (and maintain) a @EmbeddedApicurioRegistry than a mock version of the client.

I think you can just put io.apicurio:apicurio-registry-app dependency on the (test) classpath,
and it should work for any @Quarkus test; e.g. that's how we test our storages.

**Comment by EricWittmann** [comment]
Agreed, but I'm guessing lots of users will not be using Quarkus.  They are, of course, wrong... but you know. :)

**Comment by ebrard** [comment]
Actually this would be quite useful, we also use a confluent compatible mock client is a similar context but instead of starting up a Kafka instance, we use the `MockConsumer` implementation of the kafka Consumer interface, something like:
```
MockConsumer<byte[], byte[]> consumer = new MockConsumer<>(OffsetResetStrategy.EARLIEST);

// code not shown...

    consumer.schedulePollTask(
        () -> {
          consumer.rebalance(Collections.singletonList(new TopicPartition("test", 0)));
          consumer.addRecord(record);
        });
```

**Comment by famartinrh** [comment]
@tomasAlabes Hi, would be useful to use testcontainers to run the registry? if so we could provide it

**Comment by tomasAlabes** [comment]
I've never used testcontainers tbh, I don't know how lightweight they are. Still a mock client will probably be faster and easier to use but maybe it's an option to consider.

**Comment by alesj** [comment]
This is the simplest I could strip down to:
* https://gist.github.com/alesj/cea90c568c22c9bc98d1a9fb5faddff3

```
        <dependency>
            <groupId>io.apicurio</groupId>
            <artifactId>apicurio-registry-utils-embedded</artifactId>
            <version>2.0.0-SNAPSHOT</version>
        </dependency>


@QuarkusTest
public class EmbeddedTest {

    @Test
    public void testSmoke() {
        String registryUrl = "http://localhost:8081/api";
        RegistryRestClient client = RegistryRestClientFactory.create(registryUrl);
        client.listGlobalRules();
    }

}
```

That apicurio-registry-utils-embedded dependency has it all: 
* the Registry app
* a workaround for application.properties lookup and Registry app indexing
* Quarkus JUnit5 dependency

Since the Registry app is a Quarkus app, you're already using Quarkus, so adding that QuarkusTest annotation should not be that difficult.
Otoh, embedding the Registry in a different way, would mean we would just duplicate QuarkusTestExtension work.

**Comment by alesj** [comment]
> Otoh, embedding the Registry in a different way, would mean we would just duplicate QuarkusTestExtension work.

Not to mention that it's far from trivial to run an embedded Quarkus app ...

**Comment by tomasAlabes** [comment]
Hi @alesj, sorry for not answering. I'm back trying to update the registry to 2.x and my tests broke because of the change of interfaces. That reminded me of this. 
Do you have a snapshot/test jar that I could try an test replacing our `MockApicurioRegistryClient`?

**Comment by EricWittmann** [comment]
I think the easiest/best approach is probably still testcontainers with https://hub.docker.com/r/apicurio/apicurio-registry-mem

That should be a relatively quick docker image to start, but I do agree that some in-memory mock would be faster.

@famartinrh any other suggestions?

**Comment by famartinrh** [comment]
The only things I can think of are:
- testcontainers
- creating an embedded version as Ales did 
- writing a junit extension to run with `java -jar ...` the in-memory version

**Comment by carlesarnal** [comment]
We're now publishing an in-memory native image that should start quite fast and should be suitable for testing in scenarios like this one using test-containers.

**Comment by EricWittmann** [comment]
Closing this issue as done.  @carlesarnal can you link to the native in-memory image?
