### ISSUE TITLE
Various apicurio-registry-distro-connect-converter types are unresolvable by maven

### ISSUE THREAD

**Issue by jcechace** [Apicurio/apicurio-registry#1162]
For these maven bits https://mvnrepository.com/artifact/io.apicurio/apicurio-registry-distro-connect-converter/1.3.2.Final

Various types are uploaded -- jar / tar / zip. However, it seems that only the jar is actually resolvable by maven since the following does not resolve 

```
<dependency>
          <groupId>io.apicurio</groupId>
          <artifactId>apicurio-registry-distro-connect-converter</artifactId>
          <version>${version.apicurio.converter}</version>
          <type>zip</type>
</dependency>
```

The only type which can be resolved is jar. Debezium does something similar with its connectors (we publish zip and tar archives into maven central) and the type identifier can be used to determine which version is resolved.

**Comment by EricWittmann** [comment]
@riprasad Can you check into this?  The connect converter uses the maven assembly plugin to create the ZIP and TAR.GZ deployment artifacts.  The relevant pom.xml config is here:

https://github.com/Apicurio/apicurio-registry/blob/master/distro/connect-converter/pom.xml#L51-L71

It looks OK to me - because `<attach>true</attach>` is there, which should result in the built artifacts being deployed to maven central.  But perhaps I'm missing something.

Could you verify that the zip and tar.gz artifacts really **are** missing from maven central, and once that's confirmed see if you can figure out why?

**Comment by jcechace** [comment]
They are not missing from the maven central.... however, they are not resolvable as a maven dependency. One can go t the aforementioned repository link and download the artefacts manually just fine

**Comment by EricWittmann** [comment]
Thanks for the clarification.  I agree that they **should** be resolvable.

**Comment by riprasad** [comment]
> @riprasad Can you check into this? The connect converter uses the maven assembly plugin to create the ZIP and TAR.GZ deployment artifacts. The relevant pom.xml config is here:
> 
> https://github.com/Apicurio/apicurio-registry/blob/master/distro/connect-converter/pom.xml#L51-L71
> 
> It looks OK to me - because `<attach>true</attach>` is there, which should result in the built artifacts being deployed to maven central. But perhaps I'm missing something.
> 
> Could you verify that the zip and tar.gz artifacts really **are** missing from maven central, and once that's confirmed see if you can figure out why?

Sure Eric, let me check!

**Comment by riprasad** [comment]
@EricWittmann @jcechace I believe I have found the reason why the artifact type other than .jar is not getting resolved as a maven dependency, even though they are deployed in the maven central. You can see them here https://repo1.maven.org/maven2/io/apicurio/apicurio-registry-distro-connect-converter/1.3.2.Final/

 If you observe the filename closely for the tar.gz and zip type, you'll notice an extra string "**-converter**"  is being appended. 

-  apicurio-registry-distro-connect-converter-1.3.2.Final.jar
-  apicurio-registry-distro-connect-converter-1.3.2.Final**-converter**.zip
-  apicurio-registry-distro-connect-converter-1.3.2.Final**-converter**.tar.gz

That extra string is nothing but the assembly Id in the descriptor file [here](https://github.com/Apicurio/apicurio-registry/blob/master/distro/connect-converter/src/assembly/converter-distribution.xml#L5)

I have now configured the assembly plugin to not append the assembly Id and I believe this should fix the problem.

**Comment by riprasad** [comment]
Also, we cannot backport the fix for the artifacts that has already been released to maven central since we cannot upload a newer revision package with that same version number, or delete it and upload a new package at the same version.

**Comment by jcechace** [comment]
I think I should be all right with just the latest version. I will test this and let you know, thanks!

**Comment by jcechace** [comment]
@EricWittmann any chance I could get a snapshot release?

**Comment by EricWittmann** [comment]
We could do a snapshot release into github packages.  Would that work for you?

**Comment by jcechace** [comment]
Hmm... I never actually used those, but AFAIK it should work as a maven repo (similar to what jitpack does) so I guess it would work. thank you!

**Comment by jcechace** [comment]
@EricWittmann  could you give me some hints how do I get hold of the packages release via maven?  Or when the release is done? Thanks!

**Comment by riprasad** [comment]
@jcechace You'll have to do configure your maven to resolve dependencies from GitHub packages. You can follow the guide [here](https://docs.github.com/en/packages/guides/configuring-apache-maven-for-use-with-github-packages)

**Side Note:** You'll need to authenticate yourself to GitHub via a personal access token even for consuming packages. Personally, authentication for package consumption sounds crazy to me.

@EricWittmann I had raised a PR yesterday and it's merged by Fabian. We have the necessary changes and the workflow for making snapshot releases to Github packages. However, there has been a 2.0.0-SNAPSHOT release yesterday from the multitenancy branch. Since the fix was not available in that branch for the converter types, another snapshot release needs to be done from the master branch with a version other than 2.0.0-SNAPSHOT.

I think we should discuss this and decide about making snapshot releases to avoid a situation like this

**Comment by jcechace** [comment]
Yea... that authentication seems weird.

**Comment by EricWittmann** [comment]
Sorry for the delay on this.  I can't believe this is 14 days stale.  What's the status on this from everyone's perspective?  @jcechace do you have what you need yet? :(

**Comment by jcechace** [comment]
@EricWittmann  I could still use the artefacts in maven central but I guess that is not happening until new 1.3.x release. Any plans to do that?

**Comment by EricWittmann** [comment]
We don't have plans for a new 1.3.x release - we're releasing 2.0.0.Final soon.  This week or next.

**Comment by riprasad** [comment]
@jcechace Try this, This should resolve the dependency

```
<dependency>
          <groupId>io.apicurio</groupId>
          <artifactId>apicurio-registry-distro-connect-converter</artifactId>
          <version>${version.apicurio.converter}</version>
          <type>zip</type>
          <classifier>converter</classifier>
</dependency>
```

**Comment by jcechace** [comment]
That works, thanks a lot guys!
