### ISSUE TITLE
Extract JSON compatibility checking code into a separate module

### ISSUE THREAD

**Issue by blacktooth** [Apicurio/apicurio-registry#1214]
One of our use-cases require the JSON compatibility checking feature of apicurio-registry. We want to know if it's possible to extract the [JSON compatibility checker and related classes](https://github.com/Apicurio/apicurio-registry/blob/8f83adf5c2b7af616e93c831122b9ed6b37bca88/app/src/main/java/io/apicurio/registry/rules/compatibility/JsonCompatibilityChecker.java) into a separately buildable module. 

We cannot depend on the whole apicurio-registry repository as it would bring-in lot of dependencies like rest client, Protobuf, Avro, etc which we don't need. 

Can we contribute this change?

**Comment by EricWittmann** [comment]
I don't think this would be difficult.  In fact, we have our own goal of relocating the JSON compatibility checking from apicurio-registry repository into the apicurio-data-models repository.  But that will require a rewrite of the functionality and a new JSON Schema data model in apicurio-data-models, so that won't happen too soon.  Before that happens, I don't think it would be a big problem isolating the current functionality into a separate module for re-use.

@jsenko what do you think?

**Comment by blacktooth** [comment]
Since there is no standard for JSON compatibility checking (AKAIK), are you willing to publish the work done in this repository as specification for JSON schema evolution? We are open to contribution on this.

This is still open on json schema org repo, https://github.com/json-schema-org/json-schema-vocabularies/issues/5

**Comment by jsenko** [comment]
hi, I agree that moving it into a separate module should be OK for the short term. For the long term, we would like to relocate it into `apicurio-data-models`, as Eric mentioned.

**Comment by blacktooth** [comment]
Thanks for confirming! I created a [PR](https://github.com/Apicurio/apicurio-registry/pull/1240) to refactor the code to modularize this.

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-registry/pull/1302
