### ISSUE TITLE
Differences between using kafka storage and kafka stream storage for Apicurio

### ISSUE THREAD

**Issue by dev-ops-hub** [Apicurio/apicurio-registry#1370]
Based on the https://www.apicur.io/registry/docs/apicurio-registry/1.3.3.Final/getting-started/assembly-installing-registry-docker.html, we can install Apicurio Registry with either (1) Apache Kafka Storage or (2) Apache Kafka Stream Storage.

I would like to know:
1) What are the differences between using Kafka Storage and Kaf Stream Storage for Apicurio?
2) Are there any advantages and disadvantages of installing Kafka Storage over Kafka Stream Storage and vice versa?

Thanks

ALx

**Comment by EricWittmann** [comment]
I can certainly explain the differences, but you should know that both of those storages have been removed in the upcoming 2.0.0.Final release.  In 2.0.0 we support these two storages:

* apicurio-registry-sql (store data in a PostgreSQL db)
* apicurio-registry-kafkasql (store data in a Kafka cluster)

Going forward, the decision point is whether you want to store registry data in PG or in Kafka.  

That said, we did have two Kafka based storages in version 1.3.2.Final, and the difference was that the -kafka version was a more typical pub/sub approach that replicated the information across all nodes in the cluster.  The -streams version was based on Kafka Streams and instead distributed the data across all of the nodes (and then exposed a custom grpc layer so that any node can access any data, even if that data is not local).  Unfortunately both of these implementations suffered from extremely bad search performance (because we added search capabilities after designing those impls), so ultimately we replaced both with the `kafkasql` implementation which uses Kafka to replicate the data across all cluster nodes and then stores the data in an in-memory H2 database (on each node).

If you would like to know more, I'm happy to provide additional information.

**Comment by dev-ops-hub** [comment]
Hi Eric, 
Thank you for your response and explanation.  You have mentioned that in Final 2.0.0: 

"kafkasql implementation which uses Kafka to replicate the data across all cluster nodes and then stores the data in an **in-memory H2 database**"

Moving forward, does this mean that I could not store the data is a persistence storage if I chose to use kafkasql?

Thanks and regards.

**Comment by EricWittmann** [comment]
When using the **kafkasql** storage implementation, Kafka is being used as the persistent storage.  We create a topic with log compaction enabled, so messages will stick around forever.  This allows registry data to be persistent across restarts (and when starting new nodes in a cluster).  Each time a new node starts up, it will consume all of the old messages from the Kafka topic to rebuild its state.

If you wanted to use some *other* persistent storage mechanism, that's a different conversation.  :)  Or if you wanted to switch from kafkasql to sql, we are working on import/export features to handle that scenario.

**Comment by dev-ops-hub** [comment]
@EricWittmann  Thanks for your prompt response. Much apprectiaged.
