### ISSUE TITLE
Improve error handling in serdes

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#158]
If the user does not send the right thing to the topic when sending a message, the serdes Serializer doesn't throw a sensible error.  It just throws a "404 not found" error.  I think this is because it's trying to find the Schema in the registry even when the message is e.g. a simple type.  It would better if the serializer could detect that the data being sent isn't appropriate for serialization (e.g. it's just a simple type) and throw an appropriate error.

**Comment by alesj** [comment]
What do you mean by a simple type?
An example or test would be great. :)

**Comment by EricWittmann** [comment]
Yeah sorry I'm just transcribing Hugo's bugs for him into issues here.  :(  But I think what this means is that if you configure your app to use our serdes, but then you send a String,String message to the topic.  So e.g. Hugo was doing this:

```java
@ApplicationScoped
public class RegistryProducer {

    private Random random = new Random();
    private String[] symbols = new String[]{ "RHT", "IBM", "MSFT", "AMZN" };

    @Outgoing("price")
    public Flowable<KafkaMessage<String, String>> generate() {
        return Flowable.interval(1000, TimeUnit.MILLISECONDS)
                .onBackpressureBuffer()
                .map(tick -> {
                    return KafkaMessage.of(
                        symbols[random.nextInt(4)], 
                        String.format("%.2f", random.nextDouble()));
                });
    }
}
```

So he's sending a `Message<String,String>` but he configured the app to use the Avro serdes.  So the serializer tries to get the Schema from the Record...but the data is not a Record, it's a String.

**Comment by EricWittmann** [comment]
So then it tries to lookup the Schema in the registry and of course that doesn't work - error 404.

**Comment by alesj** [comment]
Looking at this ... imo, there isn't much you we can do ... since you're mixing apples with oranges ...
You're initially putting apples into registry, and then you expect the registry to understand your oranges when you say they are apples. :-)

This is just how defaults work:
* you need to register the schema before
* then you look it up, based on content macth

If you had different config + some validation rules, you would get rules validation error -- 409 afair.

**Comment by alesj** [comment]
In this case you first registered an Avro generated/based msg type.
Then you simply used String as msg type.

The problem I see here is that this Fluent magic ate away all generics.
And our serde just did the best it could to serve what was put in -- a plain string --> string schema --> failed to match Avro-record-schema with string-shema --> 404 --> expected

**Comment by EricWittmann** [comment]
Yeah I agree with pretty much all of that. :)  I do wonder though whether the serializer could/should check the type of the thing it's being asked to serialize.  If it's a String, it could fail fast with some sort of "why are you asking me to serialize a String?" error.  Unless of course there is a valid reason why the serializer might sometimes be asked to serialize a string.

Of course, I realize that String is just one possible incorrect configuration - but it does seem like the most likely one.

**Comment by EricWittmann** [comment]
It's also possible that we simply don't want to incur the expense of checking, which I think would be a fair response.

**Comment by EricWittmann** [comment]
Any thoughts on this old issue, @famartinrh ?

**Comment by famartinrh** [comment]
the fact of sending String (or Long or Boolean or whatever) objects to the avro serializers is not wrong. Those types can still be encoded using avro.
So the issue here is the mismatch between the schema in the registry and the data sent by the producer. In that case I think that is improved now, the serdes should throw reasonable errors now with human readable messages.
But in a case like this the error will still be something like artifact not found, there is no other option for this case.

**Comment by EricWittmann** [comment]
OK thanks.  Closing.
