### ISSUE TITLE
[enhancement] Allow user defined description when creating an artifact version

### ISSUE THREAD

**Issue by kilahm** [Apicurio/apicurio-registry#1629]
This proposal is an alternative solution to the problems described in #1462 and #1534 .

In brief, the 1024 limit at the DB layer of the description field for artifact versions combined with extracting the description from an uploaded OpenAPI/AsyncAPI document effectively limit the "info.description" field in the actual document.  This was resolved in ad6ad31cee6e9ea4ea749f10136d37165a5e8033 by truncating the description.

While this allows for creating the artifact version, to make the description useful in the Registry UI, the client must follow up with an update metadata call to change the version and/or artifact description to something usefully rendered in the UI.

In addition to truncating long descriptions extracted from the artifact, I think it would be good to allow the client to optionally define the version description in `POST /groups/{groupId}/artifacts/{artifactId}/versions` and `POST /groups/{groupId}/artifacts`.  This could happen via an `X-Registry-Version-Description` header, consistent with the other header-based optional inputs.

**Comment by EricWittmann** [comment]
Thanks for the request @kilahm - I don't see any reason not to implement optional user-provided descriptions when uploading  a new version.  What about the other meta-data fields users can edit, like name and tags?  Thoughts on allowing header-based values for those as well?

**Comment by kilahm** [comment]
Certainly makes sense to me to allow all editable metadata fields on version creation

**Comment by SafarMirek** [comment]
In my opinion, the way to allow users to define all editable metadata fields on new version upload is to allow them provide EditableMetaData object in the headers.

My idea is that EditableMedaData object would be JSON string and Base64 encoded to allow usage of characters which are restricted from headers by HTTP protocol. Header could be `X-Registry-Version-Metadata`.

@EricWittmann Also, implementing this feature allows Registry UI to add this feature too.

@Apicurio/developers Any thoughts on this?

**Comment by famartinrh** [comment]
I think the idea of having separated headers for each of the various metadata fields is the most reasonable idea.

Encoding `EditableMedaData` as json and then base64 and putting that in a header could cause issues due to header length.

**Comment by jsenko** [comment]
I think having it in the form of separate headers is more user friendly (e.g. with `curl`). I don't think we are in danger of violating header length limits (unless the user is trying to break things) https://stackoverflow.com/questions/686217/maximum-on-http-header-values but it seems like an unnecessary uncertainty.

**Comment by carlesarnal** [comment]
+1 for having this in separate headers.

**Comment by EricWittmann** [comment]
OK it sounds like most people think that separate headers is the right approach.  Originally that was my thought too, but let me play devil's advocate here for a moment.  Some thoughts:

* There is no length limit for an HTTP header
* HTTP headers only allow ASCII characters, which becomes a challenge for i18n (e.g. a description in Japanese)
* Even if we support separate headers, what do we do for labels and properties?  That is structured content.  Or do we simply only support Name and Description?

Does any of that info change anyone's mind?  :)

**Comment by kilahm** [comment]
OpenAPI includes a way to describe serialization of headers. Set the schema to array or object then define the `style` and `explode` keys as appropriate. That should allow generated client code to know how to encode the label list and property key value pairs.

**Comment by kilahm** [comment]
I can take a crack at a PR for the changes to the OpenAPI document.  I've been working with some Java projects at work recently, so I might even be able to implement the changes.

**Comment by SafarMirek** [comment]
I think, the fact that the HTTP headers allow only ASCII characters could be very limiting for a lot of people around the world.

**Comment by kilahm** [comment]
I can think of 2 ways to get non ascii in the description: 

1. support punycode in the header values
2. Client can make a normal put to the metadata endpoint (which is currently the case for all clients)

**Comment by carlesarnal** [comment]
+1 for separated headers

> OK it sounds like most people think that separate headers is the right approach. Originally that was my thought too, but let me play devil's advocate here for a moment. Some thoughts:
> 
>     * There is no length limit for an HTTP header

For me, having very large headers is still a bad idea, whether there are real limits or not. And, although in theory is true that there are no limits for an HTTP header in the spec, in practice, most servers define limits (e.g. Apache define 8K, quite long, but still a limit).

> 
>     * HTTP headers only allow ASCII characters, which becomes a challenge for i18n (e.g. a description in Japanese)

This is true, but we can ask users to encode their values with e.g. base64.

> 
>     * Even if we support separate headers, what do we do for labels and properties?  That is structured content.  Or do we simply only support Name and Description?
> 
> 
> Does any of that info change anyone's mind? :)

My mind just changed a bit that maybe this is not the optimal approach but I still think that it's a decent one in a balance with feature-value/eng-effort.

**Comment by EricWittmann** [comment]
Thank you everyone for the excellent discussion on this issue!

It sounds like the consensus is still to use separated headers.  I think I agree with this, because one goal we should have is to make the most likely use-case as simple as possible.  So to that end, here is a proposal:

* `X-Registry-Name` : ASCII-only value of the **name** (subject to maxlength limitations as defined by our DDL)
* `X-Registry-Description` : ASCII-only value of the **description** (subject to maxlength limitations as defined by our DDL)
* `X-Registry-Labels` : ASCII-only value of the **labels** (formatted according to OAI rules for array encoding as suggested by @kilahm )
* `X-Registry-Properties` : ASCII-only value of the **properties** (formatted according to OAI rules for object encoding as suggested by @kilahm )

In addition to these headers, I suggest we support the following:
* `X-Registry-Name-Encoded` : Same as `X-Registry-Name` but base64 encoded
* `X-Registry-Description-Encoded` : Same as `X-Registry-Description` but base64 encoded
* `X-Registry-Labels-Encoded` : Same as `X-Registry-Labels` but base64 encoded
* `X-Registry-Properties-Encoded` : Same as `X-Registry-Properties` but base64 encoded

Non-encoded headers take precedence over encoded headers if both exist.

Thoughts?

**Comment by SafarMirek** [comment]
Okey, but there are some questions:
- If we use OAI rules for array encoding in headers, there will be some characters, that users cannot use etc. ; or , or anything we use as delimeter - cookies does not support all ASCII characters for this reasons. We can implement escaping character,  but is it user-friendly?
- This could be solved by using encoded header, but only if we encode every value separately.

The last thing - defined headers values take precedence over values extracted from artifact, right?

**Comment by EricWittmann** [comment]
@SafarMirek I suggest we start out by implementing support for Name and Description.  We can tackle the Labels and Properties as a second PR.  That way we can see how we like this approach and adjust if necessary.  

Regarding the precedence - I think we should make the headers mutually exclusive - so if you include both the encoded and unencoded headers we can fail with a 409-Conflict HTTP error.

Also please let me know when you're ready to start on this, because the first thing we need to do is update the OpenAPI definition of our REST API.  That is done in a separate system, and then we codegen the JAX-RS interfaces.

**Comment by EricWittmann** [comment]
Also sorry for the delay in responding here.

**Comment by EricWittmann** [comment]
@SafarMirek Can this be closed, do you think?
