### ISSUE TITLE
Create a utility to migrate data from confluent schema registry to apicurio registry

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#172]
Should help with migration from one system to the other.

**Comment by udinnet** [comment]
Hi @EricWittmann, 
I'm trying to find the safest way to migrate 1000s of subject/versions from a confluent schema registry to Apicurio while preserving the id of the confluent registry. Is this something that is doable from this [tool](https://github.com/Apicurio/apicurio-registry/tree/main/utils/exportConfluent) you've provided?

**Comment by dweber019** [comment]
Hi @udinnet 
We did a migration with several hundreds and all went fine.

**Comment by udinnet** [comment]
Thanks @dweber019. Couple of questions
Did you also preserve the IDs from Confluent registry to Apicurio?
And do you run Apicurio with `ENABLE_CCOMPAT_LEGACY_ID_MODE=true`?

We have a requirement of preserving the IDs from Confluent as our Kafka consumers will break otherwise. This migration tool I pointed only sets the `contentId` while setting `globalId` to `-1`. So I think if we set `ENABLE_CCOMPAT_LEGACY_ID_MODE=true` it will not work as registry will start to look for `globalId` for ccompat APIs.

**Comment by udinnet** [comment]
Thanks heaps @dweber019!

**Comment by EricWittmann** [comment]
Thanks to you both for the conversation here.  Sorry I"m late to this party.

Yes we have created a Confluent Schema Registry export tool here:

https://github.com/Apicurio/apicurio-registry/tree/main/utils/exportConfluent

Good job finding that.  :)

And it should work as discussed above!  I'm going to close this as done with this context and the link above as sufficient.
