### ISSUE TITLE
Tenant Manager: is RegistryDeploymentInfoService needed?

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#1797]
This service requires a property called `registry.route.url` that has no default value.  Tenant Manager will not start up with out.  The health check service seems to use this information.

However this seems to introduce a dependency from Tenant Manager -> Service Registry.  I don't think we want that.  Is this perhaps a leftover from an earlier architecture choice related to registry instance reaping?

**Comment by famartinrh** [comment]
the dependency tenant manager -> service registry exists because in some tenant manager API endpoints it returns the full url of the tenant, and for that we need the registry route url

however we may not be using that information and building the tenant url by  hand in our control plane instead of taking what the tenant manager returns, so we could drop this dependency, wdyt?

**Comment by EricWittmann** [comment]
I would really like to avoid a tenant manager -> service registry link if we can avoid it.  However, if it's just configuration information then it could make sense.  In this case it seems like it is.  This may be even more useful when running Registry and Tenant Manager without a separate control plane.  We should decide how we expect users to run this stuff upstream... do we imagine they will create their own control plane or use the tenant manager as the control plane?  Can it perform that function by itself?

**Comment by famartinrh** [comment]
actually, reviewing the code again, the registry.route.url property is used for the liveness check and for an API endpoint that is not even used in our rest client... 

in short, we could perfectly remove the registry.route.url and drop the tenant manager -> service registry link with no issues

about running this stuff upstream you already have the answer, the multitenant UI you built, actually that UI have some logic to build the final tenant's url so, even today people would have to build their own control plane in order to have a more integrated solution that works like create registry -> return new tenant full url. 

Also if it wasn't clear `do we imagine they will create their own control plane or use the tenant manager as the control plane? Can it perform that function by itself?` -> yes, no and no
