### ISSUE TITLE
Support for multiple file artifacts (with file/folder structure)

### ISSUE THREAD

**Issue by ivangsa** [Apicurio/apicurio-registry#2015]
With some API specifications it's common to have multiple files as part of the same API

Examples:

- Asyncapi as .yml + Avros as .avsc, 
- OpenAPI + examples files, 
- gRPC are usually organized as several .proto files as well

And with some of this specifications artifacts must retain the same folder structure for editing and code generation tools to work

Current situation:

When multifile APIs are uploaded as separated artifacts, then teams consuming those artifacts must have specific knowledge of original file/folder structure for their local tools to work and this makes it cumbersome to work with..

Proposed feature:

Support multifile artifacts with file/folder structure information so uploading/downloading tools will retain original folder structure on both ends

This feature proposal is related to this one #865 as this will solve inner API references, it will not resolve inter API references...

**Comment by EricWittmann** [comment]
@ivangsa it would be interesting to get a more detailed explanation of this use case.  By that I mean:  can you give a slightly more in depth example of how developers are working with these groups of files and where the registry is expected to fit.  It seems like #865 (which is in progress) should solve your first example (Asyncapi + avro schemas).  I'm less sure about the other two, but it's possible that the use case you have in mind is not consistent with the goals of the registry project.  I'd like to understand it better!

@Apicurio/developers any thoughts on this?

**Comment by ivangsa** [comment]
ok, let me share our use case/workflow..
this is a very standard asyncapi+avro, as you can see asyncapi has references to avro files that require does files to be retain a folder structure for editing and code generation to work
![image](https://user-images.githubusercontent.com/1246876/142158934-a3fa8591-0541-43a9-8576-cb4f064bad63.png)
(absolute references won't work as it will make it harder/imposible to evolve and versioning)

This is our workflow, which is very ad hoc, it doesn't use a registry as yet:

- When API definition files are commited/merged (by designers) a build pipeline packs them as jars and deploy to a maven artifactory
- Developers then add those maven dependencies to their pom.xml, unpack them (using maven), and generate code (using maven plugins)... so they can generate both clients and producers depending on generators configuration

If we are to use an API registry like apicurio, this is what we would expect, correct me if I'm wrong or missing something or you think there is a better way:

- When API definitions are commited in the pipeline we would upload them to the registry as a single artifact retaining folder structure (using any registry client available in the pipeline)
- Developers will configure apicurio-maven-plugin for downloading one artifact files (at an specific version) to an specific folder, retaining folder structure
- Developers will configure maven code generators to point to the folder downloaded

Now, if registry doesn't support multiple files per artifact (with folder structure)

- Developers will need to configure apicurio-maven-plugin multiple times to download each artifact to an specific folder... And they will need to know original (and evolving) folder structure for their tools to work...

What happen if a new file is added, renamed, removed... to an API, they will need to keep track of that changes (and for every specific version it may differ)

This is something we want to avoid at all costs...

(regarding the other protocols, are mostly the same but less important. Designers use to split large openapi in multiple files... i.e. examples are referenced with $ref to another file by relative name $ref: 'exampes.yml#/pointer to example')

Does this makes sense? Or this is something out of the goals of registry project? Do you think there is a better way?

**Comment by ivangsa** [comment]
Hi guys, any thoughts on this?
Does this makes sense/fits into apicurio-registry?

**Comment by EricWittmann** [comment]
Hi @ivangsa thanks for the additional context/information!  That was very helpful.

I do wonder if the references feature we're working on now could solve this problem. I'm not sure and we would definitely have to experiment with it.  But here's what I'm thinking - we could modify your proposed workflow a little bit:

* When API definitions are commited in the pipeline we would upload each artifact to the registry separately, but keeping a mapping of local file name to registry coordinates.
* Developers will configure apicurio-maven-plugin for downloading the main artifact while asking the registry to also dereference any external references.  This results in a single uber specification.
* Developers will configure maven code generators to point to the uber specification.

What do you think?  I should also note that to help with the mapping between the local file path/name and the registry coordinates, you could leverage artifact properties in the registry.  E.g. you could have a "local-file-path" property added whenever the pipeline registers an artifact.

**Comment by ivangsa** [comment]
For step 2 I understand developers will pull main artifact from registry adding a boolean flag to "download also referenced artifacts", I think this can work ok...

For step 1 I'm not sure if this could lead to lots of misconfiguration errors... 
The example of the screenshot is a main asyncapi.yml artifact with 3 dereferenced avro artifacts
So designers, using maven, would need to configure 4 artifacts:
- one for each avro files
- one for asyncapi with references to avro artifacts: with group/artifactIds, file/paths and versions

I see a lot of room to misconfiguration errors when things starts evolving... 

From a registry point of view I think it can work... Maybe it's just a matter of finding the right configuration settings with some sensible defaults for uploading..

```xml
<artifact>
    <groupId>TestGroup</groupId> 
    <artifactId>FullNameRecord</artifactId>
    <file>${project.basedir}/src/main/resources/schemas/asyncapi.yml</file>
    <references>
       <includes>**/*avsc</includes><!-- relative to main file: behind the curtains they become artifacts -->
    </references>
</artifact>
```

**Comment by EricWittmann** [comment]
Ah yes - the part I thought about but didn't type with my fingers is this:  I think we need to enhance the maven plugin so that it can (optionally?) register any referenced local files in addition to the main artifact being registered.  So the maven plugin would crack open the content of the artifact being registered (OpenAPI, AsyncAPI, JSON Schema, Avro, etc) and try to figure out what the references are.  This will allow the plugin to register the main artifact and also anything that artifact references.  This should work really well for some types (OpenAPI, AsyncAPI) but perhaps less well for others (Avro, WSDL).  In the former case, the references should be fairly explicit - by the nature of the specification (e.g. the $ref will be a pointer to a local file). For the latter case (such as Avro or WSDL) the references might not be a pointer to a file but rather a `QName` of some kind.  In those cases we might need to allow the maven plugin to be configured with the references - or some sort of hint.

But I think in the use-case you've described, it should work really well.  The plugin would also add the additional meta-data I've suggested (via properties).  That will allow interesting queries to be possible.

**Comment by EricWittmann** [comment]
@carlesarnal any thoughts on this?

**Comment by EricWittmann** [comment]
I should note that whatever enhancements we make as I've described above in the maven plugin - those features should be available in some sort of standalone tool as well.  We don't want to **require** the maven plugin for this sort of thing to work.

**Comment by ivangsa** [comment]
sounds good to me!!

**Comment by carlesarnal** [comment]
First of all, sorry for the late response on this, lots of things happening right now.

While I do think the references feature we're working on could be useful for this particular usecase, I don't think it will 100% cover it. The main concern I see here is to maintain the folder structure. I can imagine expanding the groups feature allowing some sort of granularity (sub-grups?) obviously with some limitations, but that's I think an option.

Alternatively, as Eric described, we can expand the references feature to add that information about the folder structure to the reference and when downloading the content dereferenced, use that information to maintain the folder structure.

**Comment by mcerkez88** [comment]
For me main problem here is that apicurio treats every artefact as its own entity and doesn't have notion of artefact references and by extension dependencies between artefacts. Since every supported artefact type has different notion of inclusions and dependencies with WSDL and XSD being particular challenge with a lot of edge cases this is probably a deep rabbit hole to solve.

With that in mind I propose that such artefacts be handled like zip archive and treated as one artefact. Downside is that we essentially tie all objects within a bundle with same matedata. Possibly we could expand zip into separate artefacts with registry. Sometimes it makes sense to do so.

Personally I have solved this problem by using absolute references in async api specification. I'm not confident that it can work in a general case.

```        
traits:
  - "$ref": http://localhost:8080/apis/registry/v2/ids/globalIds/38
  - "$ref": http://localhost:8080/apis/registry/v2/ids/globalIds/40
```

and I can have explicit references to other managed artefacts and it works great for my scenario. I have two problems with this scenario that I have to solve.

1. How to maintain globalIds consistent across multipe environments (maybe this is a non issue have to see in practice)
One solution would be to expand REST API to enable getting artefacts by coordinates (group/name/version)
2. If Apicurio api is secured I have to have a way for tools to use secured access for references resolution (this may prove a challenge depending on a toolchain used in development)

Does this makes sense?

**Comment by ivangsa** [comment]
> ... expanding the groups feature allowing some sort of granularity (sub-grups?) obviously with some limitations, but that's I think an option.

limitations doesn't sound as a good option to me ;-)

> Alternatively, as Eric described, we can expand the references feature to add that information about the folder structure to the reference and when downloading the content dereferenced, use that information to maintain the folder structure.

A think this can solve this functionality...
Do you see storing this folder structure in references as something that can be implemented?

**Comment by carlesarnal** [comment]
> > ... expanding the groups feature allowing some sort of granularity (sub-grups?) obviously with some limitations, but that's I think an option.
> 
> limitations doesn't sound as a good option to me ;-)
> 
> > Alternatively, as Eric described, we can expand the references feature to add that information about the folder structure to the reference and when downloading the content dereferenced, use that information to maintain the folder structure.
> 
> A think this can solve this functionality... Do you see storing this folder structure in references as something that can be implemented?

Yes, I do. Right now the way it works is that you specify the reference name when you create the artifact with references, so I don't see why we can't expand that to add this kind of metadata. It may be a bit challenging, but it'll be fun to solve.

**Comment by ivangsa** [comment]
that sound awseome!
When this is on its way I may be able to help with the tooling, maven plugin, rest client... to make them behave as a single artifact (the main artifact and it's dependencies) rom the end user point of view as described avobe...

**Comment by carlesarnal** [comment]
We implemented support for this in the maven plugin (and obviously the server part for supporting references). [Here's](https://github.com/Apicurio/apicurio-registry/tree/main/examples/avro-maven-with-references-auto) an example using the plugin.
