### ISSUE TITLE
API unable to detect yaml format and artifact type

### ISSUE THREAD

**Issue by Bewi42** [Apicurio/apicurio-registry#2143]
Hello,

Using version 2.1.4.Final

With this sample OAS file in yaml format :
```
openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
```

I try to create an artifact with following curl command :
`curl -s -X POST -H 'X-Registry-ArtifactId: sample-api' -d '<file_content>' http://localhost:8080/apis/registry/v2/groups/my-group/artifacts`
Response is :
`{"message":"Failed to discover artifact type from content.","error_code":400,"detail":"InvalidArtifactTypeException: Failed to discover artifact type from content.","name":"InvalidArtifactTypeException"}`

I have to force artifact type and content format to let the API know what my schema is :
`curl -s -X POST -H 'X-Registry-ArtifactId: sample-api' -H 'Content-type: application/yaml' -H 'X-Registry-ArtifactType: OPENAPI' -d '<file_content>' http://localhost:8080/apis/registry/v2/groups/my-group/artifacts`
Then artifact is created, but when you try to visualize it in UI, it says "Artifact isn't a valid OpenAPI structure" and fails to generate documentation. The title and description are not extracted from the source document.

**Comment by jsenko** [comment]
I've tried an alternative validator and it should be a valid schema. I'll look into it, thanks for the report.

**Comment by jsenko** [comment]
I found the cause. The problem was that the content was not correctly read as yaml, and therefore Registry could not examine it to determine the artifact type.  You have to modify your `curl` command to use the following:
1. `-H 'Content-Type: application/x-yaml'`
1. Use `-data-binary` option instead of `-d`.

This worked for me `curl -s -X POST -H 'X-Registry-ArtifactId: sample-api' -H 'Content-Type: application/x-yaml' --data-binary '@data.yaml' http://localhost:8080/apis/registry/v2/groups/my-group/artifacts`

The first point may be an issue on our side, i.e. we should support other common content type strings for yaml, such as `application/yaml`. However the second point is the root cause, and is related to how `curl` sends data. If you use `-d` parameter, curl removes some whitespace characters, in this case newlines, which caused the yaml deserailizer to read `openapi: 3.0.0info:` instead of `openapi: 3.0.0\ninfo:`.

**Comment by Bewi42** [comment]
Hello,
Thanks for your answer. I have tried the "x-yaml" content type as well as binary data and it works.
But when I download the schema from the registry after creation, I get a JSON content instead of YAML, is it the expected behavior ? Apicurio stores everything in JSON format ?

**Comment by jsenko** [comment]
Hi, yes it does convert it at the moment, but we're working on changes to enable keeping the format that was uploaded.
