### ISSUE TITLE
New release plan

### ISSUE THREAD

**Issue by hhkkxxx133** [Apicurio/apicurio-registry#2274]
Hello,

Apologies for frequent follow up. I would like to know if there would be a recent new release on the library as I recently have a bug fix merged for the protobuf-schema-utilities module which is required for our integration work. 

Thanks in advance!

**Comment by EricWittmann** [comment]
Oof - this was 12 days ago!  Sorry for the delay.  I'll schedule an upstream release for this week.  We have a couple of fairly interesting/significant features waiting to be merged, so I was going to wait for those before cutting a release.  But there's no real need to wait.

@Apicurio/developers any objections to an upstream release?

**Comment by riprasad** [comment]
Please merge the below two PRs before doing the release. No objections otherwise

https://github.com/Apicurio/apicurio-registry/pull/2296
https://github.com/Apicurio/apicurio-registry/pull/2298

@carlesarnal Registry-examples builds are failing. In case you have time, it might be a good idea to fix it before the release.
https://github.com/Apicurio/apicurio-registry-examples/runs/5363339871?check_suite_focus=true

**Comment by EricWittmann** [comment]
@riprasad I fixed the examples build, but it still failed during the release for the reasons I outlined in gchat with you.  FYI :)  But I did merge both those PRs before releasing.  So that's good.

@hhkkxxx133 Release was done today and is ready to go now.

https://github.com/Apicurio/apicurio-registry/releases/tag/2.2.1.Final
