### ISSUE TITLE
Create a comprehensive list of all available Registry configuration options

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#2509]
This is mostly env. variables. Include such a list to the documentation. I imagine a table (or multiple by group) with the following columns:
- Variable name
- Description
- Type & Valid values
- Available since (Version)

Related to:
- https://github.com/Apicurio/apicurio-registry-operator/issues/167

**Comment by andreaTP** [comment]
Hi @jsenko !
I took a stab at generating such documentation.
Here you have a very very draft: https://github.com/andreaTP/apicurio-registry/commit/cc6dad3694063f598ce6f214462b27907de209a9

The current result can be seen here: https://github.com/andreaTP/apicurio-registry/blob/cc6dad3694063f598ce6f214462b27907de209a9/out.md

I have a few follow-up questions:
- Do you want this documentation to be manual or automatic?
- How should `RegistryProperties` be handled as they are dynamically instantiated?
- How should "Available Since" be extracted or inferred?
- Should we include property mapped directly from Quarkus or not? (or should we have some sort of allow/deny list here?)
- Quarkus provides out-of-the-box environment variables for configuration values, should we show only the custom (nonstandard) ones or should we discriminate?

**Comment by EricWittmann** [comment]
Fabulous start.  wdyt @jsenko ?

**Comment by jsenko** [comment]
- I think manual only is not a feasible option with the number of properties we currently have, but special cases like the `RegistryProperties` would probably need a separate section in the docs.
- For the Available Since, we can either create a custom annotation for this, or process multiple Registry versions using the script and compare. The custom annotation could also include some type of label or category, similar to what `io.apicurio.common.apps.config.Dynamic` has. This would require us revisit the properties or provide the extra info gradually.
- I think we can show the custom ones where defined, and use the standard conversion where not.

We should also create some kind of internal guidelines on naming the properties (across projects also) to maintain consistency, but this is just a nice-to-have and not critical.

**Comment by andreaTP** [comment]
- added to my prototype the "automatic extraction" of "Available From"
- leaving `RegistryProperties` with the current "best-effort"

You can see the result here:
https://github.com/andreaTP/apicurio-registry/blob/generate-config-docs/out.md

Please, play a little with it and provide some guidance on how to proceed, e.g. how to automate the generation for the docs, if there is anything already in place I can hook into etc. etc.

**Comment by andreaTP** [comment]
Getting back to this, I think that my automatic extraction of "available since" is too much complexity/tech debt for such a simple thing (also my implementation won't work for versions containing > 1 digits numbers e.g. `2.1.10` 😅 ).

I'm more in favor of an extra annotation like `io.apicurio.common.apps.config.Dynamic`, but I would need details regarding "some type of label or category" we wanna include in a first version.

We can also initially populate the additional annotation with the values (available since) extracted by the hacked script.

**Comment by EricWittmann** [comment]
Could we generate a JSON formatted index of properties for every version?  If we had that, it should be reasonably simple to automate the "available since" information.

That said, I'm also happy with an annotation based solution.  :)

**Comment by andreaTP** [comment]
> Could we generate a JSON formatted index of properties for every version

Of course, where should we store it? Can it also feed the final documentation?
Automating "available since" is definitely possible and even "reasonably simple" but it needs maintenance and edge cases handling. We also need to agree on a few assumptions that might change over time:
 - source of truth (maven central / Docker / GH tags / something else?)
 - stored vs. re-calculated (in case of backports)
 - ...
 
On the other hand, manually adding this information in an annotation, is an operation that is required once and we don't need any specific logic to maintain its extraction.

**Comment by jsenko** [comment]
I'm leaning towards slowly adding the annotations as well. The label idea would be to make it easier for users to find config that they need, e.g. `security`, `storage`, `multitenancy`, etc. It could just be a part of the annotation.

**Comment by EricWittmann** [comment]
> > Could we generate a JSON formatted index of properties for every version
> 
> Of course, where should we store it? Can it also feed the final documentation? 

As an asset for each release.  Part of the release automation would be to compare with the asset in the previous release.

**Comment by andreaTP** [comment]
> As an asset for each release. Part of the release automation would be to compare with the asset in the previous release.

Not unreasonable, but I think that is not strictly "necessary", in the sense that it opens the doors to edge cases, e.g. this will break if we start to support LTS versions.
To support LTS we need to ask every release a human operator to fill the previous version for the current release, again doable, but it increases the complexity etc.

On the other hand something that we can easily do is to populate, from the results of the script, the mentioned annotations once(in an initial PR). As soon as the annotations are in the code everything will flow without the need of extra comparisons leaving us less automation to maintain.

wdyt?

**Comment by andreaTP** [comment]
Started:
https://github.com/Apicurio/apicurio-common-app-components/pull/44
as a baseline and:
https://github.com/Apicurio/apicurio-registry/pull/2715
to show the possible outcome.

**Comment by EricWittmann** [comment]
You've convince me.  :)

My only concern then is how to enforce the presence of the new annotation in locations where it's required.  I assume that is every usage of `@ConfigProperty` or whatever the mp-config annotation is called.  Should we have validation that we've annotated all usages of that with the new `@Info` annotation?

**Comment by andreaTP** [comment]
> Should we have validation that we've annotated all usages of that with the new `@Info` annotation?

The "quick and dirty" check would be to include the doc generation in CI and fail if it is not present: https://github.com/Apicurio/apicurio-registry/pull/2715/files#diff-cee4b1ee8c71fd92cc76f5677f2edf839eb2857f5fac3d0295c340df133b2e96R169

A cleaner solution would be to perform the validation in a simple annotation processor.

@EricWittmann do you have ideas/proposals/references on how to integrate this list in the docs?

**Comment by EricWittmann** [comment]
Yeah I think having something in CI would be useful.  Just an annotation processor that can fail if someone adds a config property without annotating it with the new annotation.

I haven't thought much about the integration with the docs.  That's a good question for @smccarthy-ie though!

**Comment by smccarthy-ie** [comment]
Great work, thanks @andreaTP! Some of these config properties are for features that are currently available upstream-only (e.g., multitenancy). 

Wondering should we flag properties like that that are not supported downstream? Or is this a separate concern, i.e., dependent on conversations with PM for each release? WDYT @EricWittmann? 

From a docs perspective, we can add conditional text tags in the `.adoc` to hide upstream-only features if needed, like we already do elsewhere in the docs (e.g.,`ifdef::apicurio-registry[]`).

**Comment by andreaTP** [comment]
Thanks for chipping in @smccarthy-ie !
Technically, if we need to distinguish such properties, we can do it with an additional flang in the `@Info` annotation.
But, let see what @EricWittmann suggests 🙂

**Comment by EricWittmann** [comment]
Good thinking @smccarthy-ie - the question is do we want to bleed downstream/upstream details into the upstream repo?  That's what we would be doing if we add another field to the `@Info` annotation.  Are there other options?

**Comment by smccarthy-ie** [comment]
Yes, upstream/downstream features are subject to changes from PM, so best to only show all available options upstream. We can hide content in the `.adoc` file downstream or create separate downstream-only doc if needed.
