### ISSUE TITLE
Replace org.everit. library to networknt library to support 2020 or at least 2019 standard JSON schema

### ISSUE THREAD

**Issue by Gourav2912** [Apicurio/apicurio-registry#2553]
APiCurio is currently supporting org.everit library for schema validation.
org.everit library supports only draft 4,6 and 7.
APICurio should use networknt validator library to support newer JSON schema.

**Comment by Gourav2912** [comment]
networknt library could also help in solving validation error messages in case of multiple validation issues.
Current library is only providing below error message in case of validation failure
2 schema violations found

**Comment by jsenko** [comment]
I think networknt could be easily adapted to replace everit for JSON schema validation. However, it would not be suitable for use in JSON schema compatibility checker, because networknt does not internally parse the schema into a dedicated model, and works with JSON nodes directly. We'll need to discuss this with the team.

**Comment by Gourav2912** [comment]
@EricWittmann By any chance support of 2019 Json schema in SDK is planned?

**Comment by jsenko** [comment]
We have decided to [add JSON Schema support to Apicurio Data Models](https://github.com/Apicurio/apicurio-epics/issues/99) since none of the third-party libraries fit well.
