### ISSUE TITLE
Avro compatibility check does not work correctly for Enum types

### ISSUE THREAD

**Issue by bastijns-jeroen** [Apicurio/apicurio-registry#2572]
Hi,

I was testing the APIcurio registry's capabilities and encountered a bug concerning schema evolution with enum types.
When extending an enum type with a new symbol in forward compatibility mode the validation does not fail.
Tested versions are 2.2.2, 2.2.3 and 2.2.4.
In the test case there are no defaults defined for the enum type, nor for the field.

Version one of the schema:
```json
{
  "namespace" : "be.ordina.jworks.contractfirstasyncapi",
  "type" : "record",
  "name" : "VehicleRefueled",
  "fields" : [
    {"name":"licensePlate","type":"string", "doc": "The license plate of the vehicle"},
    {"name":"fuelType",
      "type": {
        "type":"enum",
        "name": "FuelType",
        "symbols": ["GASOLINE","DIESEL","LPG", "CNG", "ELECTRICITY"]
      }
    },
    {"name":"fuelAmount", "type":"double", "default":0.0},
    {"name":"fuelUnit",
      "javaAnnotation": [ "java.lang.Deprecated(since = \"2\", forRemoval = true)" ],
      "type": {
        "name": "FuelUnit",
        "type":"enum",
        "symbols": ["LITER", "KWH"]
      }
    }
  ]
}
```

Version two of the schema that should be invalid because I'm extending the FuelType enum without defaults declared:
```json
{
  "namespace" : "be.ordina.jworks.contractfirstasyncapi",
  "type" : "record",
  "name" : "VehicleRefueled",
  "fields" : [
    {"name":"licensePlate","type":"string", "doc": "The license plate of the vehicle"},
    {"name":"fuelType",
      "type": {
        "type":"enum",
        "name": "FuelType",
        "symbols": ["GASOLINE","DIESEL","LPG", "CNG", "ELECTRICITY", "TEST"]
      }
    },
    {"name":"fuelAmount", "type":"double", "default":0.0},
    {"name":"fuelUnit",
      "javaAnnotation": [ "java.lang.Deprecated(since = \"2\", forRemoval = true)" ],
      "type": {
        "name": "FuelUnit",
        "type":"enum",
        "symbols": ["LITER", "KWH"]
      }
    }
  ]
}
```

**Comment by EricWittmann** [comment]
Interesting use case!  There is always a bit of disagreement over whether modifying an enum constitutes a compatibility failure or not.

What I can say is that we're actually just using the default compatibility checking that comes in the Avro library.  You can see our implementation here:

https://github.com/Apicurio/apicurio-registry/blob/main/schema-util/avro/src/main/java/io/apicurio/registry/rules/compatibility/AvroCompatibilityChecker.java

Note our use of the Apache Avro library for this.  We're very open to suggestions about how to improve things though!

**Comment by jstanik** [comment]
Hello,

I'd say that the "bit of disagreement" about the compatibility should end by the Avro specification, which is in the section [Schema Resolution](https://avro.apache.org/docs/1.11.1/specification/#schema-resolution) quite clear that:

> if both are enums: if the writer’s symbol is not present in the reader’s enum and the reader has a default value, then that value is used, **otherwise an error is signalled.**

I've checked the Confluent Schema Registry and it handles the enum evolution correctly. I also checked the Avro library and the problem seems to really be there:

```
SchemaValidator validator = new SchemaValidatorBuilder().canBeReadStrategy().validateLatest();

Schema newSchema = createEnum("Color", null, "example", List.of("RED", "GREEN", "BLUE"));
Schema oldSchema = createEnum("Color", null, "example", List.of("RED", "GREEN"));

validator.validate(newSchema, List.of(oldSchema)); // DOES NOT FAIL BUT IT SHOULD!
```

@EricWittmann you said you were open to suggestions. I am afraid the suggestion would be to implement the validation by other means than using the Avro library that has this bug. Sorry, I don't have a better one.

**Comment by jstanik** [comment]
@EricWittmann I did a bit of a "research" and I found that others also use the Avro API to do the validation which can detect the enum incompatibilities. But instead of using `SchemaValidator` the `org.apache.avro.SchemaCompatibility` is used instead. So the following case reports the FORWARD incompatibility between the old and the new schema (with Avro 1.11.1):

```
Schema newSchema = createEnum("Color", null, "example", List.of("RED", "GREEN", "BLUE"));
Schema oldSchema = createEnum("Color", null, "example", List.of("RED", "GREEN"));

SchemaPairCompatibility result = SchemaCompatibility.checkReaderWriterCompatibility(
    oldSchema,
    newSchema
);

if (result.getType() != SchemaCompatibilityType.COMPATIBLE) {
  throw new IllegalStateException("New schema is not FORWARD compatible.");
}
```

So maybe the suggestion would be to use the `SchemaCompatibility` class to perform the validation of all the schema compatibility rules (BACKWARD, FORWARD, ...)

**Comment by EricWittmann** [comment]
Thanks for all the excellent information, @jstanik !

**Comment by jstanik** [comment]
@jsenko @EricWittmann @carlesarnal , thanks for providing fix for this issue.
