### ISSUE TITLE
Trying to register a schema which references twice the same complex type throws SchemaParseException

### ISSUE THREAD

**Issue by TomBillietKlarrio** [Apicurio/apicurio-registry#2739]
We're using the dynamic schema registration of apicurio, and since the latest upstep, we're facing the following error from time to time:
```
org.apache.avro.SchemaParseException: Can't redefine: com.xxx.yyy
```

Digging a bit deeper in the code, it seems this is a regression introduced in `2.2.2.Final` (2.2.1 was still working). More specific here:
https://github.com/Apicurio/apicurio-registry/blob/a28493615587946eb41b48fd778cf758e6129c71/serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroSchemaParser.java#L75
The `resolvedReferences` contains duplicates, which makes the `schema.toString()` crash.

I created a reproduction unit test. It tries to register the following schema:
```
{
  "namespace": "com.kubetrade.schema.trade",
  "type": "record",
  "name": "AvroSchemaF",
  "fields": [
    {
      "name": "schemaE1",
      "type": "com.kubetrade.schema.trade.AvroSchemaE"
    },
    {
      "name": "schemaE2",
      "type": "com.kubetrade.schema.trade.AvroSchemaE"
    },
    {
      "name": "key",
      "type": "string"
    }
  ]
}
```
However I don't see exactly on how this should be fixed, can somebody assist with that?

PR: https://github.com/Apicurio/apicurio-registry/pull/2740

**Comment by TomBillietKlarrio** [comment]
Yes, I tried building from `main`, and the unit test I added in https://github.com/Apicurio/apicurio-registry/pull/2740 also fails on `main`. It's actually a variation of the test you refer to.
So no, I don't think it's fixed. I don't think I can re-open the issue though?

**Comment by carlesarnal** [comment]
Ok, I understand now this issue better, thanks for the reproducer. The issue the other PR fixed is actually different. I have created https://github.com/Apicurio/apicurio-registry/pull/2775 that actually solves this issue, thanks!

**Comment by TomBillietKlarrio** [comment]
I tried to deploy the current version on main, and it looks like it's not completely solved yet. I get the following exception now:
```
io.apicurio.registry.rest.client.exception.RestClientException: 
io.apicurio.registry.storage.impl.sql.jdb.RuntimeSqlException: 
org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY_KEY_2 ON PUBLIC.ARTIFACTREFERENCES(TENANTID, CONTENTID, NAME) VALUES ('_', 865, 'io.debezium.data.VariableScaleDecimal', 121)"; SQL statement:
INSERT INTO artifactreferences (tenantId, contentId, groupId, artifactId, version, name) VALUES (?, ?, ?, ?, ?, ?) [23505-197]
```
I'm using apicurio with kafka as storage. The apicurio version deployed is `2.2.5.Final`, but I assume the fix is in the client-library only?

**Comment by carlesarnal** [comment]
The fix consists of two parts, one in the client, and one in the server. 2.2.5.Final is still affected by this. We will cut a new release tomorrow containing the fix.

**Comment by TomBillietKlarrio** [comment]
> The fix consists of two parts, one in the client, and one in the server. 2.2.5.Final is still affected by this. We will cut a new release tomorrow containing the fix.

OK thanks

**Comment by TomBillietKlarrio** [comment]
I can confirm it works fine now in `2.3.0.Final`, thanks for the fix.

**Comment by MobAbi** [comment]
Hi all,
I'm quite new to apicurio and I'm not sure this belongs here?
I modeled a set of AVRO messages, and from time to time I see the following error messages:

{"log":"Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: \"UNQ_CONTENT_1_INDEX_6 ON PUBLIC.CONTENT(TENANTID, CONTENTHASH) VALUES ('_', '4e9cb19ed020d896658d9b93d162b8e52e153538a43880a93c884a46952cace0', 57)\"; SQL statement:\r\n","stream":"stdout","time":"2022-10-30T09:08:36.447388749Z"}
{"log":"INSERT INTO content (tenantId, contentId, canonicalHash, contentHash, content, artifactreferences) VALUES (?, ?, ?, ?, ?, ?) [23505-197]\r\n","stream":"stdout","time":"2022-10-30T09:08:36.447459133Z"}
{"log":"\u0009at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)\r\n","stream":"stdout","time":"2022-10-30T09:08:36.447467328Z"}
{"log":"\u0009at org.h2.message.DbException.get(DbException.java:179)\r\n","stream":"stdout","time":"2022-10-30T09:08:36.447521714Z"}
{"log":"\u0009at org.h2.message.DbException.get(DbException.java:155)\r\n","stream":"stdout","time":"2022-10-30T09:08:36.447534852Z"}
{"log":"\u0009at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:101)\r\n","stream":"stdout","time":"2022-10-30T09:08:36.447543242Z"}
{"log":"\u0009at org.h2.mvstore.db.MVSecondaryIndex.requireUnique(MVSecondaryIndex.java:236)\r\n","stream":"stdout","time":"2022-10-30T09:08:36.447618655Z"}
{"log":"\u0009at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:202)\r\n","stream":"stdout","time":"2022-10-30T09:08:36.447631089Z"}
{"log":"\u0009at org.h2.mvstore.db.MVTable.addRow(MVTable.java:732)\r\n","stream":"stdout","time":"2022-10-30T09:08:36.447638397Z"}
{"log":"\u0009at org.h2.command.dml.Insert.insertRows(Insert.java:182)\r\n","stream":"stdout","time":"2022-10-30T09:08:36.447723119Z"}
{"log":"\u0009at org.h2.command.dml.Insert.update(Insert.java:134)\r\n","stream":"stdout","time":"2022-10-30T09:08:36.44773564Z"}
{"log":"\u0009at org.h2.command.CommandContainer.update(CommandContainer.java:102)\r\n","stream":"stdout","time":"2022-10-30T09:08:36.447743542Z"}
{"log":"\u0009at org.h2.command.Command.executeUpdate(Command.java:261)\r\n","stream":"stdout","time":"2022-10-30T09:08:36.44775065Z"}
{"log":"\u0009at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)\r\n","stream":"stdout","time":"2022-10-30T09:08:36.447803579Z"}
{"log":"\u0009at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)\r\n","stream":"stdout","time":"2022-10-30T09:08:36.447811346Z"}
{"log":"\u0009at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)\r\n","stream":"stdout","time":"2022-10-30T09:08:36.44785358Z"}
{"log":"\u0009at io.apicurio.registry.storage.impl.sql.jdb.UpdateImpl.execute(UpdateImpl.java:44)\r\n","stream":"stdout","time":"2022-10-30T09:08:36.447929417Z"}
{"log":"\u0009... 197 more\r\n","stream":"stdout","time":"2022-10-30T09:08:36.447938849Z"}

Any idea of tipps what the problem could be?

**Comment by carlesarnal** [comment]
Hi @MobAbi, if you're having problems please, open a new GH issue instead of commenting on a closed and solved one. Also do not forget to add some context there, like what you're trying to achieve and, if possible, also share a reproducer of your problem.
