### ISSUE TITLE
redhat amqstream registry frontend : no refresh cache without ctrl + F5

### ISSUE THREAD

**Issue by mpusg** [Apicurio/apicurio-registry#2793]
Hi all,

During my test on the apicurio suite, I found a bug in the frontend of the registry. For example, when I change the status of an artifact, I don't see the new status without refresh by flush the browser's cache with ctrl+f5. 

![registry-front](https://user-images.githubusercontent.com/98844079/190393806-8ec6bf89-4127-48bc-83f6-7e253b34bfb4.png)

Tested on edge, chrome and firefox. 

Thanks.

**Comment by EricWittmann** [comment]
How are you changing the status, via the REST API I assume?  If yes, and you then do a simple reload of the page it doesn't update the status??  It's definitely a bug if the browser is caching information about the artifact - that should be marked in the HTTP response of the API call as `no-cache`.

Can you open the Network tab in your browser webtools and see if you can get any information about the HTTP responses of the API calls the page is making?  Perhaps see if there is any caching happening on the API endpoint that ends in `/meta`?

**Comment by mpusg** [comment]
Hi Eric,

Yes, you're absolutely right. 

I activated a version of schema like follow. 

```bash
curl -X PUT https://broker-schema-registry-infra-kafka-sbiz.apps.dev.ocp.dev.biz.lodh.com/apis/registry/v2/groups/default/artifacts/com.company.movie/versions/2/state -H 'content-type: application/json' -d '{"state":"ENABLED"}'

curl https://broker-schema-registry-infra-kafka-sbiz.apps.dev.ocp.dev.biz.lodh.com/apis/registry/v2/groups/default/artifacts/com.company.movie/versions | jq
{
	"count": 1,
	"versions": [
		{
			"name": "com.company.movie",
			"description": "MPU test",
			"createdOn": "2022-10-05T08:02:36+0000",
			"createdBy": "",
			"type": "AVRO",
			"labels": [
				"avro",
				"kafka",
				"ocpdeploy"
			],
			"state": "ENABLED",
			"globalId": 18,
			"version": "2",
			"contentId": 7
		}
	]
}
```
... 

The headers of the response : 
```
HTTP/1.1 200 OK
date: Mon, 10 Oct 2022 10:10:09 GMT
expires: Tue, 10 Oct 2023 10:10:09 GMT
cache-control: public, max-age=31536000
content-type: application/json
content-length: 325
```

**Comment by EricWittmann** [comment]
Fascinating!  We should be setting it to `no-cache`.  None of the REST API calls should be cached, for this very reason.  Interestingly, here's what I'm seeing in our Operate First deployment:

![image](https://user-images.githubusercontent.com/1890703/195197494-c0ff61ae-9cd4-4a3c-97ba-7a500439a9e2.png)

Different than what you're seeing but still not right.

But when I run registry locally via podman I get this:

![image](https://user-images.githubusercontent.com/1890703/195197942-9e7818ea-6e61-4003-bc77-9b8b1b9d60eb.png)

That's what I expect to see, with `Cache-Control` set to `nocache` and `Expires` set to yesterday (and `Pragma: no-cache` for good measure).

I'm not sure why those headers are not being applied.

How exactly are you deploying and running the registry?

**Comment by EricWittmann** [comment]
Oh another question:  what is the full URL to that `/meta` api endpoint?

**Comment by mpusg** [comment]
The registry is running and managing inside openshift from RedHat so finally by kubernetes. So we have an operator that manage the lifecycle of the apicurio registry pod (deploy, update..) and same thing for the avro schemas thought Custom Resource Definition. 
versions : 
- operator 2.0.5+0.1648813064.p
- registry 2.0.2.Final-redhat-00001

Maybe we have bad configuration inside a pod or a middleware that insert or mutate the `cache-control` header. 

The full URL looks like to `https://broker-schema-registry.company.com/apis/registry/v2/groups/default/artifacts/com.company.movie/meta`
I'm sorry. I can't provide you a real URL because of confidentiality.

**Comment by EricWittmann** [comment]
No that's OK.  FYI there is a much newer version of the registry that you might want to upgrade to, but it's not relevant for this issue.

I wonder if there is some Envoy magic we can do to add the cache control headers in.  That said, we're seeing similar issues with those headers on some of our deployments, so we're investigating.  Of course, since you're on the product version that might not help you in the near term (you would need to wait for another on-prem release).

@jsenko or @andreaTP While I'm looking into the cache control filter, what do you think about using Envoy to add cache control headers to the responses when deployed to k8s/openshift?

**Comment by EricWittmann** [comment]
I have some updates on this.  First, some context/info.

### How do cache control headers get added?
We have a servlet filter that is responsible for adding the correct cache control headers to all HTTP responses.  This filter can be found here:

https://github.com/Apicurio/apicurio-registry/blob/main/app/src/main/java/io/apicurio/registry/ui/servlets/ResourceCacheControlFilter.java

It will add cache control headers **no matter what**.  One of two possible actions is taken by the filter:

1. _The request is an API call and should not be cached_:  the filter will add `Date`, `Expires`, `Pragma`, and `Cache-Control` headers to instruct the browser to **never cache** the response
2. _The request is anything else (e.g. a static HTML or JS file):  the filter will add `Expires` and `Cache-Control` headers to instruct the browser to cache for 1 year.

The filter is configured to run against every request to the application:

https://github.com/Apicurio/apicurio-registry/blob/main/app/src/main/resources-unfiltered/META-INF/web.xml#L26-L34

### What's happening really?
When running locally, everything described above works fine.  But when deployed to K8s/OpenShift, the filter appears to not be working.

### Is the filter being invoked?
When running locally **yes**, when deployed to K8s/OpenShift, **no**.

### How do you know?
I've added some temporary debug statements to the cache control filter.  I see expected output when running locally but not when running in K8s/OpenShift.  In the latter deployment environment, the cache control filter seems to only be invoked for **some** URLs but not all - and notably not for the API calls.

### Is multi-tenancy the problem?
I don't think so because this GitHub issue originated from someone running the RHI-SR (Red Hat product version) which does not support multi-tenancy.  However I have not independently tested running a local multi-tenant configuration.

### Now what?
I'm looking for suggestions!  Why is the filter not being invoked when the app is deployed to k8s?  Is there something different about the request that causes the filter to not match?

IDEAS?

**Comment by EricWittmann** [comment]
Note: here is an example of correct vs. incorrect HTTP response headers for the `/system/info` API endpoint:

https://gist.github.com/EricWittmann/603fc7f9b42ba4cdf926a3fbc5082b08

First is from Operate First (incorrect) and second is from a local install (correct).

**Comment by jsenko** [comment]
Agreed, I think adding a proxy such as Envoy could be a solution. You can use Lua code to add a header like this:
```
filters:
- name: envoy.filters.network.http_connection_manager
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
    http_filters:
    - name: envoy.filters.http.lua
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
        inline_code: |
          function envoy_on_request(request_handle)
            # Logic to decide whether to apply the header...
            request_handle:headers():add("Cache-Control", "no-cache, no-store, must-revalidate")
          end
```

**Comment by EricWittmann** [comment]
Nice.  If that can be matched to `*/apis/*` it should do the trick.

**Comment by mpusg** [comment]
Hi @EricWittmann, @jsenko 

Thanks for your interesting investigations :) ! 

We are submitted to redhat management version and we must care about the version of confluent / apicurio client inside springboot and quarkus applications. 

Do you know which version solve this issue ? No need to fix it with a workaround like install an http proxy because we aren't in production yet. 
Thanks for your proposals.

**Comment by EricWittmann** [comment]
The bug you're hitting is fixed in our most recent version, which is Red Hat Integration Service Registry 2.3.  It was just released last week.

**Comment by jsenko** [comment]
This issue looks resolved, I'm closing it.
