### ISSUE TITLE
Default schema value of the record is `null` for `BYTES` type after Avro deserialization

### ISSUE THREAD

**Issue by vjuranek** [Apicurio/apicurio-registry#2980]
## Description

**Registry
Version**: 2.2.5 (same issue also after upgrading to 2.3.0)

It seems that when the Kafka Connect record is deserialized from Avro format using `io.apicurio.registry.utils.converter.AvroConverter` as shown bellow, default value for `BYTES` type is always `null`, although original record has set the default value to non-null value and such non-null value is also in the Apicurio registry.

Example Avro records deserialization:
```
SchemaAndValue avroValueWithSchema = avroValueConverter.toConnectData(record.topic(), avroValueBytes);
```

Convert configuration is as follows:
```
config.put("apicurio.registry.url", APICURIO_URL);
config.put("apicurio.registry.auto-register", true);
config.put("apicurio.registry.find-latest", true);
```

Relevant part of the schema in Apicurio schema registry:
```
            {
              "name": "H",
              "type": [
                {
                  "type": "bytes",
                  "connect.version": 1,
                  "connect.parameters": {
                    "length": "10"
                  },
                  "connect.default": "QgE=",
                  "connect.name": "io.debezium.data.Bits"
                },
                "null"
              ],
              "default": "B\u0001"
            },
```

Example schema for the record before serialization:
```
         {
            "name": "H",
            "index": "7",
            "schema": {
              "name": "io.debezium.data.Bits",
              "type": "BYTES",
              "optional": "true",
              "default": [
                66,
                1
              ],
              "version": "1"
            }
          },
```

Schema for the same record after deserialization:
```
          {
            "name": "H",
            "index": "7",
            "schema": {
              "name": "io.debezium.data.Bits",
              "type": "BYTES",
              "optional": "true",
              "default": null,
              "version": "1"
            }
          }
```

We hit this issue in Debezium testsuite after switching from Confluent schema registry to Apicurio. With Confluent registry everything works. In the test we serialize the records to Avro, deserialize back and check (besides other things) that the schema is still the same, you can see the relevant part of the test [here](https://github.com/debezium/debezium/blob/main/debezium-core/src/test/java/io/debezium/data/VerifyRecord.java#L836-L842).

**Comment by Naros** [comment]
We have a relational column defined with a default value but is nullable; this translates to a Connect Schema Field marked optional but with a default value.  In this use case, the connect field is defined as an `INT16` that is optional with a default value of `1` (short).  

We observe that the returned schema from the avro converter, while it returns the field as `INT16` and optional, the default value is lost and the converter returns a value of `null` rather than `1` (short).

During stepping through a debugging session, we found that the `INT16` field is mapped to a `UnionSchema` and at this [line](https://github.com/Apicurio/apicurio-registry/blob/main/utils/converter/src/main/java/io/apicurio/registry/utils/converter/avro/AvroData.java#L1699-L1700), the enclosing method argument `fieldDefaultVal` is set to `1` but the union switch branch explicitly passes `null` to the recursive method call and that results in the schema created with a `null` default value rather than the expected.

**Comment by carlesarnal** [comment]
So, this is indeed a bug with the default value when it's present. But it's not actually that `INT16` is mapped to a UnionSchema, the fact is that by definition that is a UNION schema, with the null value and the `INT16`, as you can see in this example here:
```
[{"type":"int","connect.doc":"int16test field","connect.default":2,"connect.type":"int16"},"null"]
```

The main problem is that we're not handling the default value properly in this situation, let me address that. Essentially, we're not getting the default value properly from the connect schema.

**Comment by carlesarnal** [comment]
I have created (and linked) a PR that fixes this problem.
