### ISSUE TITLE
Inconsistent validation behavior between UI and REST API

### ISSUE THREAD

**Issue by Hongbo-Miao** [Apicurio/apicurio-registry#3314]
# Description

**Registry Version**: `quay.io/apicurio/apicurio-registry/2.3.1.Final`
**Persistence type**: kafkasql

### Environment

Kubernetes v1.26.3

### Steps to Reproduce

My global validation rule is "disabled":

<img width="949" alt="image" src="https://user-images.githubusercontent.com/3375461/236010424-8f3373b7-de27-419b-b0f5-69c5f468c68c.png">

Manually uploading an invalid **motor.avsc** (`-` should not be in the name):

```json
{
  "type": "record",
  "namespace": "com.hongbomiao",
  "name": "hm.motor-value",
  "fields": [
    {
      "name": "timestamp",
      "type": "long"
    },
    {
      "name": "current",
      "type": "double"
    },
    {
      "name": "voltage",
      "type": "double"
    },
    {
      "name": "temperature",
      "type": "double"
    }
  ]
}
```

will show error

<img width="946" alt="image" src="https://user-images.githubusercontent.com/3375461/236010146-689017e0-edfc-44c3-b6f4-b40f5ef80e45.png">

which is great!

However, using REST API will succeed

```shell
curl --location 'http://localhost:8080/apis/registry/v2/groups/hm-group/artifacts' \
--header 'Content-type: application/json; artifactType=AVRO' \
--data '{
    "type": "record",
    "namespace": "com.hongbomiao",
    "name": "hm.motor-value",
    "fields": [
        {
            "name": "timestamp",
            "type": "long"
        },
        {
            "name": "current",
            "type": "double"
        },
        {
            "name": "voltage",
            "type": "double"
        },
        {
            "name": "temperature",
            "type": "double"
        }
    ]
}'
```

To let REST API fail, I need enable global validation rule, then it will fail with error

```json
{
    "causes": [],
    "message": "Syntax violation for Avro artifact.",
    "error_code": 409,
    "detail": "SchemaParseException: Illegal character in: motor-value",
    "name": "RuleViolationException"
}
```

### Expected vs Actual Behaviour

I was expecting UI and REST API have consistent behaviors when global validation rule disabled (also be consistent when enabled). 😃

**Comment by carlesarnal** [comment]
Hi @Hongbo-Miao,

I guess it depends on how you see it, but there's no real inconsistency here, probably more of a bad error message in the UI. The reason for the failure in the UI, when no validation is enabled, is (I suppose) that you're probably letting the server figure out the artifact type for you instead of selecting it in the dropdown. If you do that, the server will try to guess the type and the way it does that for Avro is by actually validating the content, thus why you're getting that error. If you select Avro in the artifact type dropdown the UI will succeed just like the API.

As I said, not really an inconsistency but more a bad error message in the UI.

**Comment by Hongbo-Miao** [comment]
Thanks @carlesarnal for clarification! Feel free to close the issue or leave it open until the error message be updated to be more clear. 😃
