### ISSUE TITLE
Enable $ref validation for JSON Schemas.

### ISSUE THREAD

**Issue by avi5kdonrh** [Apicurio/apicurio-registry#3335]
### Feature or Problem Description

I have two schemas:

1. I upload this first:

```
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://example.com/schema1.json",
    "type": "object",
    "$defs": {
        "name": {
            "type": "string"
        }
    }
}

```
2. I upload this next:
```
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://example.com/schema2.json",
    "type": "object",
    "properties": {
        "external": {
            "$ref": "schema1.json#/$defs/test"
        }
    },
    "$defs": {
        "personal": {
            "email": {
                "type": "string",
                "format": "email"
            },
            "birthday": {
                "type": "string",
                "format": "date"
            }
        }
    }
}
```

As you can see the "$ref": "schema1.json#/$defs/test" does not exist in the first schema but currently I can successfully upload the second schema as well because the $refs are not resolved/validated.

### Proposed Solution

If $ref points to an invalid location, the schema upload should fail.

**Comment by EricWittmann** [comment]
This is an interesting topic, and @carlesarnal and I discussed it recently.  Here's how I see it.  We plan on introducing a new artifact Rule that, when enabled, would validate Artifact References.  There are three phases of validation, I think:

1. Validate that all $ref's (or equivalent depending on artifact type) have been mapped to some registry coordinates.  This basically means that every reference in the content of the artifact being registered must have a corresponding reference mapping.
2. Validate that the artifact coordinates for all artifact references actually exist in the Registry.
3. Validate that the actual content reference resolves to something in the target artifact.  So if it's a JSON Schema with a $ref of `schema1.json#/$defs/FooType` then we would load `schema1.json` and check for the existence of `$defs/FooType`.

We are definitely going to implement (1) and (2).  But (3) is a bit of a grey area.  We agree it can make sense, but at the same time we're not sure if that would set up an expectation that external (outside the registry) references should also be resolved and validated.  The latter is something we will definitely not do, since it opens a severe attack vector (downloading content from an external URL).

**Comment by carlesarnal** [comment]
Closing as this is a bit stale and I think having 1 and 2 implemented is more than sufficient for the use case.
