### ISSUE TITLE
Add ability to configure post_logout_redirect_uri 

### ISSUE THREAD

**Issue by justinaslelys** [Apicurio/apicurio-registry#3400]
### Feature or Problem Description

Currently `post_logout_redirect_uri` is coded to be the current page where user clicks "Logout" in Apicurio ("[window.location.href](https://github.com/Apicurio/apicurio-registry/blob/65a368b83481f47948284b34f82b5220d6bfa225/ui/src/services/auth/auth.service.ts#L178)")
It worked fine until I decided to enhance Browser flow by configuring Identity Provider Redirector (so that user would be redirected to idp without the need to see Keycloak's login form). After this got configured I have a bit weird situation - once I click Logout in Apicurio, I am redirected to the same page I were before clicking Logout and then I am automatically redirected to idp and voilà - I am logged in again. 

I am unsure how common this situation may be but maybe it's worth to look at it.

### Proposed Solution

An ability to customize `post_logout_redirect_uri` would be nice, although I am not sure what would be the best location to customize it.

### Additional Context

Here is the screenshot showing all the browser requests after a single Logout click in Apicurio registry when Identity Provider Redirector is configured in Keycloak.
![apicurio-logout](https://github.com/Apicurio/apicurio-registry/assets/888441/7ce520a3-70e6-4e1e-b383-758007d61981)

**Comment by EricWittmann** [comment]
I've added a new configuration property to control this behavior.  The PR is here:

* https://github.com/Apicurio/apicurio-registry/pull/5199

The config property is `apicurio.ui.auth.oidc.logout-url`.

Like you, I'm not entirely sure what the value should be.  You could just use `about:blank` for now I guess.  I think perhaps I'll open another GH issue to introduce a new "You've been logged out" landing page.  That's slightly harder to implement than you might think, due to how the UI is built and protected by OIDC.  Having a page that will render when **not logged in** is possible but not elegant.  Which is why I didn't do it in PR #5199.
