### ISSUE TITLE
No artifact with ID 'kreditkartenantrag2_output_table_topic-value' in group 'null' was found

### ISSUE THREAD

**Issue by JensVial** [Apicurio/apicurio-registry#3541]
Hello,

we are using Kafka-Connect with the JDBC-Connector.
We configured a new SINK-Connector with the following config

```json
{
	"connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
	"dialect.name": "PostgreSqlDatabaseDialect",
	"table.name.format": "kreditkartenantrag2_output_table",
	"topics": "kreditkartenantrag2_output_table_topic",
	"batch.size": "5000",
	"connection.attempts": "3",
	"value.converter.schema.registry.url": "http://apicurio.apicurio.svc:8080/apis/ccompat/v7",
	"delete.enabled": "false",
	"auto.evolve": "true",
	"name": "Kreditkartenantrag_2_Sink",
	"auto.create": "false",
	"value.converter": "io.confluent.connect.avro.AvroConverter",
	"connection.url": "jdbc:postgresql://postgres.postgres.svc:5432/masterdata?user=xxxxxxxxxx&password=xxxxxxxxxxxxxxx",
	"insert.mode": "upsert",
	"key.converter": "org.apache.kafka.connect.storage.StringConverter",
	"pk.mode": "record_value",
	"pk.fields": "id"
}
```

For Apicurio we are using the following image apicurio/apicurio-registry-sql:2.4.3.Final.

We created the Schema in the default-group

![grafik](https://github.com/Apicurio/apicurio-registry/assets/13627632/9ce1387e-a318-4a3b-a515-8a12645c7c60)
![grafik](https://github.com/Apicurio/apicurio-registry/assets/13627632/e9959b2d-0925-4a1f-b48a-14573ee683d9)

Our Kafka-Connector throw an error because trying fetch the schema without a group ("saying no artifact-id in group 'null' was found)

![grafik](https://github.com/Apicurio/apicurio-registry/assets/13627632/bfe72e05-ebd2-4087-9a51-740570a608b2)

We have found the following entry on this topic at redhat, but have no access for redhat
https://access.redhat.com/solutions/7009768

Is this an knowing issue and is there a fix for it?

**Comment by m-kay** [comment]
Unfortunately the error `no artifact-id in group 'null' was found` is always thrown if for any reason a suitable schema could not be found and the actual reason for that is not really clear. I mostly had this problem because normalization of the schema seems not to work in the confluent compatiblity API, even though there is a parameter `normalize` in the v7 confluent API. 

What usually worked for me is to exactly register the schema in the same format as the serializer is requesting it, which means I had to remove tabs, linebreaks and withespace manually before uploading the schema.

This is still quite shaky and should be handled by apicurio in my opinion. So the schema should be normalized when creating it on the server side and when a schema is requested it should be normalized for the comparison the same way.

**Comment by EricWittmann** [comment]
This is the way. :)

I think @carlesarnal is working on getting `normalize` to work as expected.  We have a feature in Apicurio Registry that we call `canonicalize` which I suspect is the same thing.  That works in our first-party API just fine, so it might just be a matter of getting that feature used when `normalize=true` in the ccompat API.

**Comment by carlesarnal** [comment]
So, as Eric pointed out, this is caused (usually), by normalization of the schema. As @m-kay also pointed out, it should be Apicurio Registry duty to normalize the the schema. The main problem with that is that our normalization will never be the same as the Confluent one, since they're doing a few things that are causing schemas to be essentially not compatible. For instance, they're doing field re-ordering in Avro and that basically makes the two Avro schemas incompatible since any binary data serialized using one of the schemas incompatible with the other one.

What we do, as Eric correctly pointed out, is schema canonicalization so, whenever a schema lookup request is made, if the normalize parameter is set to true, we compare the canonical values for the schemas (the schema present in the request and the potential matches). This is and has been a sensible approach since we apply the same transformation to the already present schema and to the request one. There might be some situations/schemas where the schema lookup might fail, so we always appreciate reproducers/example schemas to close gaps where possible.

That said, and, again, as @m-kay said, obviously registering the schema as the serializer requests it will work just fine.

I'm currently working on a set of improvements that will address some situations with schema normalization, but, as I said, there are reasons for our normalization of the schema to not be exactly the same.

**Comment by carlesarnal** [comment]
The PR I linked will solve most of the issues with schema normalization. That said, and as I pointed out, there are an there will always be some (minor) differences between the two applications.
