### ISSUE TITLE
Improve artifact creation and update

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#362]
Artifact must exist (and there must be some content) to create artifact rules. Therefore users cannot define artifact rules (specifically application type `CREATE`) before actually adding the content for the first time (global rules work). The same applies in case of metadata. I suggest we separate creation of an artifact into just defining an empty version sequence (so the creation will not require initial content), and the first content will be added by an update operation. This may allow us to remove distinction between rule application type `CREATE` and `UPDATE`.

Alternatively, we could remove distinction between creation and updating of an artifact, because we are adding content in both cases.

See also #359

**Comment by EricWittmann** [comment]
I'm not sure I see how these two options solve the same problem.  First, I don't think I'm in favor of allowing a user to CREATE an artifact without content, although I see the motivation for doing that (you could then create the artifact, set some rules, and then [try to] upload the content).  Right now this would only be relevant for Validity checking since Compatibility requires multiple versions.  But it complicates the user's interaction with the REST API when I think we should be simplifying it.  It seems like global rules are sufficient (but could perhaps be improved to be more granular) for enabling Validity checking for CREATE operations.

On the other hand, removing the distinction between CREATE and UPDATE I think is more interesting.  If we have just one operation "CreateOrUpdate" then I think that would be quite valuable, and would make e.g. the serdes implementations easier.  However, there is also value to having just CREATE and just UPDATE operations.  So I'm thinking perhaps we add a query param to e.g. the UPDATE operation to let the server create the artifact if it does not yet exist.

**Comment by alesj** [comment]
>> So I'm thinking perhaps we add a query param to e.g. the UPDATE operation to let the server create the artifact if it does not yet exist.

And perhaps similar to CREATE, to actually do an update if it already exists ... ?

**Comment by EricWittmann** [comment]
Yeah we could certainly have query params on both CREATE and UPDATE so *either* of them could be turned into a CreateOrUpdate operation.  Should be disabled by default to preserve current "strict" behaviour.

**Comment by EricWittmann** [comment]
@carlesarnal I am going to add query parameters as described in this issue.  Then you can work on the back-end implementation of the param.  I'll open a draft PR as a starting point.

**Comment by EricWittmann** [comment]
https://github.com/Apicurio/apicurio-registry/pull/472
