### ISSUE TITLE
"Discarded a (presumed) tombstone message" logs at application start up

### ISSUE THREAD

**Issue by derickmr** [Apicurio/apicurio-registry#3644]
Hi team,

I have an Apicurio application running on AWS on an environment that I exclusively use for load testing. I've recently noticed that whenever I try to re-deploy the Apicurio application solely on this environment, the application will log a bunch of below messages:

```
2023-09-12 00:09:45 INFO <> [io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage] (KSQL Kafka Consumer Thread) Discarded a (presumed) tombstone message with key: ArtifactRuleKey [groupId=null, artifactId=my.test.4b2433fe-eb1f-466e-aa3b-9698fd0aad81, ruleType=VALIDITY]
2023-09-12 00:09:45 INFO <> [io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage] (KSQL Kafka Consumer Thread) Discarded a (presumed) tombstone message with key: ArtifactRuleKey [groupId=null, artifactId=my.test.4b2433fe-eb1f-466e-aa3b-9698fd0aad81, ruleType=COMPATIBILITY]
```

First, what do these messages mean?

I'm suspicious this is correlated with a load test I performed a while ago. In that setting, I was creating a bunch of artifacts per second, and deleting them right after (ie ~5 seconds), all this through a script. Might be important to say that I have both VALIDITY and COMPATIBILITY global rules turned on in my registry. The reason why I deleted the artifacts is that I didn't want them to stay in my registry as they were being used just for testing sake. Can this test have caused it somehow? And if so, how do I fix it?

The implications of this is that the application takes a while to startup, and even causes the deployment entirely fail some of the times. I see that `StorageLivenessCheck` stays as `DOWN` until the messages stop. 

For replication, perhaps a way is to set a load test deployment, enable the validity/compatibility global rules, then create a bunch of artifacts and almost instantly deletes them (preferably through a script), then try to re-deploy the application. Sorry if this is very specific. 

Registry version: apicurio-registry-kafkasql:2.4.2

Appreciate any help!

**Comment by derickmr** [comment]
Hi @jsenko, @EricWittmann, @carlesarnal, just checking if there are any updates on this one?

**Comment by jsenko** [comment]
Hi Derick,

When a piece of data is deleted, Registry sends a so-called tombstone message to the Kafka topic. It is a message with a key for the given data, in this case identifying an artifact rule, but with an empty value. This is done to allow [Kafka log compaction](https://kafka.apache.org/documentation/#compaction), where Kafka can either keep only the last message for a given key, or delete all messages for a given key from the topic if the last message has an empty value. This helps to reduce topic size, which in you case is probably pretty big because of the load testing. This is causing both the long startup times and the logs about the tombstone messages. You can enable log compaction using the `cleanup.policy=compact` and the related settings, which should resolve the issue. One of our planned features to reduce the startup times and the topic size is to implement checkpointing, so the Registry would not have to read the entire topic on startup in the future.

**Comment by EricWittmann** [comment]
Hey @derickmr - let's start with what it means.  You're obviously using the Kafka storage (not postgres).  So when using Kafka for storage, log compaction is enabled, so that the messages are persisted. In Kafka, a tombstone message is one that is intended to provide a hint to Kafka log compaction that all previous messages **of this type** can be compacted/removed (including the tombstone).  

In registry, an example of that would be whenever you disable a global rule.  In the DB disabling a global rule is removing a row from the global rule table.  In Kafka it would be adding a tombstone message for the "Set Global Rule Config" message.  Essentially telling Kafka that it can compact/remove all those messages.  The idea is that replaying all of the Kafka messages should restore the internal state, and it doesn't matter how many messages you have of type "Set Validity Rule to XYZ" - only the last one matters. And if the last one is "disable" then we can just tombstone all of them.

Do you have log compaction enabled for the topic?  That's the first question.  It sounds like maybe not - in which case you would have a ton of messages in the topic that could probably be compacted.

Well damn - as I'm typing this I see @jsenko has already answered.  LOL

I'll just post what I've typed in case I have said anything beyond Jakub's excellent answer.  :)

**Comment by derickmr** [comment]
Awesome, thanks for the info @EricWittmann, @jsenko - as a follow-up, the `kafkasql-journal` topic already has `cleanup.policy=compact` set. Are there any other configs (perhaps storage ones?) I should be looking at?

**Comment by derickmr** [comment]
To be more specific, these are the current configs for that topic:

```
retention.ms 7 days
retention.bytes Infinite
delete.retention.ms 1 day
cleanup.policy compact
compression.type producer
segment.bytes 1 GiB
message.format.version 2.5-IV0
max.compaction.lag.ms Infinite
file.delete.delay.ms 1 minute
max.message.bytes 1 MiB
min.compaction.lag.ms 0
message.timestamp.type CreateTime
segment.ms 7 days
message.timestamp.difference.max.ms Infinite

message.downconversion.enable true
segment.jitter.ms 0
flush.ms Infinite
flush.messages Never
preallocate false
index.interval.bytes 4 kiB
min.cleanable.dirty.ratio 50%
segment.index.bytes 10 MiB
```

**Comment by derickmr** [comment]
Hi @EricWittmann, @jsenko - just checking if you have any other suggestions about this? I tweaked the configs yesterday and got from 40gb to 24gb on that topic, but still seems a little too much.

**Comment by EricWittmann** [comment]
24gb is quite a lot, for sure.  How many artifacts/versions would you say you have in the registry?

One thing you can do to cleanup the topic is:

1. Export all of the data from the registry (there is a REST API for this)
2. Shut down the registry
3. Delete all messages from the Kafka topic
4. Start the registry back up
5. Import the data that was exported in (1) above (also a REST API for this)

That will result in ONLY the messages in the topic that you actually need.

**Comment by derickmr** [comment]
Another piece of information that might be relevant: my load test script was generating a unique id for each schema I was posting/deleting every time. So, I was not using the same schema for deletion. I guess this means that there are millions of unique tombstone messages with unique keys in Kafka, and it won't compact any further as each of the message keys are unique. This would explain that amount of data.

**Comment by derickmr** [comment]
@EricWittmann currently I only have ~10 schemas in the registry right now. But during the load test I created/deleted millions of schemas. To be more specific, that topic contains over 75M messages at the moment

**Comment by EricWittmann** [comment]
Thanks for the additional information - very interesting!  I thought Kafka deleted the tombstone messages, but it seems clear from your experience that is not happening.  There is some discussion about this here:

https://stackoverflow.com/questions/46632713/kafka-not-deleting-key-with-tombstone

Ultimately we plan to fix this once we implement snapshotting, which will allow the kafka topic to have older messages (any messages older than the most recent snapshot) get cleaned up.  Then we won't need log compaction at all, and message retention can be configured relative to snapshot generation.

But until then, my advice is the export/import procedure I wrote about above.

**Comment by EricWittmann** [comment]
Yes I think you have summarized it correctly.  The only I would add is that I'm surprised that the tombstone messages were not successful in cleaning up this problem . My understanding of Kafka suggests that when log compaction was done, all of those messages (including the tombstone messages) would get deleted.  We would need to further analyze your kafka topic to determine if **only** the tombstone messages have remained, or if **all** of the messages are still there.

So we still IMO have a mystery here - why did the tombstoning not work as I expected?  Is it because there is a configuration problem (I cannot spot one if there is) or is my understanding incorrect (very possible)?

**Comment by derickmr** [comment]
Thanks @EricWittmann, I've did some digging into that topic on Friday. These are my findings:

Apicurio creates 4 entries on the `kafkasql-journal` when we create an artifact:

```
Key
{
	"tenantId": "_",
	"uuid": "dd23d803-f3c2-49d1-8037-c1346e14518c"
}

Value:
{
	"action": 1
}

Key
{"tenantId":"_","contentHash":"b2dadbe1a7a8d7da8094e818a269fe224fb60bfb3b2f9c8dd22a48d0fbb3b988","contentId":2}

Value:
AgEAAABANDk3ZWFhZmMyOWFhYjg1OGVkYmM4NzdlMTJlZDJkZmJhNmFjZjc4NmViNjk4ODI2MjUyYmE2MmIxMWRkOTI2ZAAAA8V7CiAgIm9wZW5hcGkiOiAiMy4wLjIiLAogICJpbmZvIjogewogICAgInRpdGxlIjogIkVtcHR5IEFQSSIsCiAgICAidmVyc2lvbiI6ICIxLjAuNyIsCiAgICAiZGVzY3JpcHRpb24iOiAiQW4gZXhhbXBsZSBBUEkgZGVzaWduIHVzaW5nIE9wZW5BUEkuIgogIH0sCiAgInBhdGhzIjogewogICAgIi93aWRnZXRzIjogewogICAgICAiZ2V0IjogewogICAgICAgICJyZXNwb25zZXMiOiB7CiAgICAgICAgICAiMjAwIjogewogICAgICAgICAgICAiY29udGVudCI6IHsKICAgICAgICAgICAgICAiYXBwbGljYXRpb24vanNvbiI6IHsKICAgICAgICAgICAgICAgICJzY2hlbWEiOiB7CiAgICAgICAgICAgICAgICAgICJ0eXBlIjogImFycmF5IiwKICAgICAgICAgICAgICAgICAgIml0ZW1zIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgIH0KICAgICAgICAgICAgfSwKICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogIkFsbCB3aWRnZXRzIgogICAgICAgICAgfQogICAgICAgIH0sCiAgICAgICAgInN1bW1hcnkiOiAiR2V0IHdpZGdldHMiCiAgICAgIH0KICAgIH0KICB9LAogICJjb21wb25lbnRzIjogewogICAgInNjaGVtYXMiOiB7CiAgICAgICJXaWRnZXQiOiB7CiAgICAgICAgInRpdGxlIjogIlJvb3QgVHlwZSBmb3IgV2lkZ2V0IiwKICAgICAgICAiZGVzY3JpcHRpb24iOiAiQSBzYW1wbGUgZGF0YSB0eXBlLiIsCiAgICAgICAgInR5cGUiOiAib2JqZWN0IiwKICAgICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAgICJ4dGVhbV9pZCI6IHsKICAgICAgICAgICAgInR5cGUiOiAiaW50ZWdlciIKICAgICAgICAgIH0sCiAgICAgICAgICAieHRlYW1fbmFtZSI6IHsKICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIgogICAgICAgICAgfQogICAgICAgIH0KICAgICAgfQogICAgfQogIH0KfQAAAAA=

Key
{"tenantId":"_","uuid":"85253273-9386-427d-b542-109246adad95"}

Value:
{"action":1}

Key
{"tenantId":"_","artifactId":"8d620ce0-bd2b-4f7c-917e-65b7f7832764","uuid":"092be179-1de4-4040-82c4-529ac66505e2"}

Value:
{"action":1,"metaData":{"name":"Empty API","description":"An example API design using OpenAPI."},"globalId":4,"artifactType":"OPENAPI","contentHash":"b2dadbe1a7a8d7da8094e818a269fe224fb60bfb3b2f9c8dd22a48d0fbb3b988","createdBy":"","createdOn":1694807605081}
```

Note that the key for each message is unique.

And, whenever we do a delete operation, it creates 5 entries in the topic:

```
Key:
{"tenantId":"_","artifactId":"8d620ce0-bd2b-4f7c-917e-65b7f7832764","uuid":"507e565c-adb5-493d-bb65-76edcbf8078b"}

Value:
{"action":3}

Key:
{"tenantId":"_","artifactId":"8d620ce0-bd2b-4f7c-917e-65b7f7832764","ruleType":"INTEGRITY"}

Value
null

Key
{"tenantId":"_","artifactId":"8d620ce0-bd2b-4f7c-917e-65b7f7832764","ruleType":"COMPATIBILITY"}

Value:
null

Key
{"tenantId":"_","artifactId":"8d620ce0-bd2b-4f7c-917e-65b7f7832764","ruleType":"VALIDITY"}

Value:
null

Key
{"tenantId":"_","artifactId":"8d620ce0-bd2b-4f7c-917e-65b7f7832764","version":"1"}

Value:
null
```

Note that 4 of the 5 messages are tombstone (value is null), and still all of the keys are unique (they are not even equal to the ones from the creation/update operations).

So, all the messages have unique keys and there's nothing to Kafka to really compact or delete.

I've noticed that those 9 records on the topic equal to ~23kb (some of them store the whole schema definition). meaning that those 75M messages we have on the topic in the load test env match the 24gb storage we see.

To me, this seems to explain why the topic contains so much data - as all the message keys are unique and none get compacted/deleted, and there are 9 messages per create/delete combination. 

@EricWittmann @jsenko does this make sense? Do you see any path going forward with this? I will check the KSQL driver code you've been using in Apicurio - that might be the culprit for the messages not having the same key.

**Comment by derickmr** [comment]
I just did a little bit of investigation in the [KafkaSqlSubmitter](https://github.com/Apicurio/apicurio-registry/blob/3b730e06a32355ebb5a42eadd7529050f3a4152c/storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlSubmitter.java#L78). I see that the keys are being intentionally created using composed data. For instance, for the submit artifact event: https://github.com/Apicurio/apicurio-registry/blob/3b730e06a32355ebb5a42eadd7529050f3a4152c/storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlSubmitter.java#L139, we have that composed by tenant/group/artifactId, but whenever we delete the artifact, there isn't a tombstone message that matches that key. That seems to be the case for all messages that are sent for the creation, and aren't 'tombstoned' when there's a delete event. 

That would explain why the data is kept in the topic even when not relevant anymore.

@EricWittmann @jsenko @carlesarnal do you guys see possible solutions for this? I am glad to help on this and contribute with the fix if there's one here to be developed! Just let me know your thoughts on this before jumping into any coding.

**Comment by EricWittmann** [comment]
> Thanks @EricWittmann, I've did some digging into that topic on Friday. These are my findings:

Nice, let's dig into it.  The first thing to understand (I'm refreshing my  memory in the code) is that the serializer adds a single byte to the key to indicate its **type**.  So even when the JSON value of two keys look the same, they might not be.

> Apicurio creates 4 entries on the `kafkasql-journal` when we create an artifact:

We can ignore anything where the key is just a `tenantId` and a `uuid`.  Those are always requests for IDs of some kind (e.g. `globalId` or `contentId`).  I'll annotate that here, but going forward we can ignore those.  ID requests can never be compacted because they are essentially counters.

> 
> ```
> Key
> {
> 	"tenantId": "_",
> 	"uuid": "dd23d803-f3c2-49d1-8037-c1346e14518c"
> }
> 
> Value:
> {
> 	"action": 1
> }
> 
> Key
> {"tenantId":"_","contentHash":"b2dadbe1a7a8d7da8094e818a269fe224fb60bfb3b2f9c8dd22a48d0fbb3b988","contentId":2}
> 
> Value:
> AgEAAABANDk3ZWFhZmMyOWFhYjg1OGVkYmM4NzdlMTJlZDJkZmJhNmFjZjc4NmViNjk4ODI2MjUyYmE2MmIxMWRkOTI2ZAAAA8V7CiAgIm9wZW5hcGkiOiAiMy4wLjIiLAogICJpbmZvIjogewogICAgInRpdGxlIjogIkVtcHR5IEFQSSIsCiAgICAidmVyc2lvbiI6ICIxLjAuNyIsCiAgICAiZGVzY3JpcHRpb24iOiAiQW4gZXhhbXBsZSBBUEkgZGVzaWduIHVzaW5nIE9wZW5BUEkuIgogIH0sCiAgInBhdGhzIjogewogICAgIi93aWRnZXRzIjogewogICAgICAiZ2V0IjogewogICAgICAgICJyZXNwb25zZXMiOiB7CiAgICAgICAgICAiMjAwIjogewogICAgICAgICAgICAiY29udGVudCI6IHsKICAgICAgICAgICAgICAiYXBwbGljYXRpb24vanNvbiI6IHsKICAgICAgICAgICAgICAgICJzY2hlbWEiOiB7CiAgICAgICAgICAgICAgICAgICJ0eXBlIjogImFycmF5IiwKICAgICAgICAgICAgICAgICAgIml0ZW1zIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgIH0KICAgICAgICAgICAgfSwKICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogIkFsbCB3aWRnZXRzIgogICAgICAgICAgfQogICAgICAgIH0sCiAgICAgICAgInN1bW1hcnkiOiAiR2V0IHdpZGdldHMiCiAgICAgIH0KICAgIH0KICB9LAogICJjb21wb25lbnRzIjogewogICAgInNjaGVtYXMiOiB7CiAgICAgICJXaWRnZXQiOiB7CiAgICAgICAgInRpdGxlIjogIlJvb3QgVHlwZSBmb3IgV2lkZ2V0IiwKICAgICAgICAiZGVzY3JpcHRpb24iOiAiQSBzYW1wbGUgZGF0YSB0eXBlLiIsCiAgICAgICAgInR5cGUiOiAib2JqZWN0IiwKICAgICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAgICJ4dGVhbV9pZCI6IHsKICAgICAgICAgICAgInR5cGUiOiAiaW50ZWdlciIKICAgICAgICAgIH0sCiAgICAgICAgICAieHRlYW1fbmFtZSI6IHsKICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIgogICAgICAgICAgfQogICAgICAgIH0KICAgICAgfQogICAgfQogIH0KfQAAAAA=
> 
> Key
> {"tenantId":"_","uuid":"85253273-9386-427d-b542-109246adad95"}
> 
> Value:
> {"action":1}
> 
> Key
> {"tenantId":"_","artifactId":"8d620ce0-bd2b-4f7c-917e-65b7f7832764","uuid":"092be179-1de4-4040-82c4-529ac66505e2"}
> 
> Value:
> {"action":1,"metaData":{"name":"Empty API","description":"An example API design using OpenAPI."},"globalId":4,"artifactType":"OPENAPI","contentHash":"b2dadbe1a7a8d7da8094e818a269fe224fb60bfb3b2f9c8dd22a48d0fbb3b988","createdBy":"","createdOn":1694807605081}
> ```

The messages above correspond to:

1. Request a new `contentId` (counter)
2. Store content (note: content is stored separately from artifacts to save space)
3. Request a new `globalId` (counter) (note: every version of every artifact is assigned a unique globalId)
4. Create new artifact

None of these can be compacted.  I mentioned why in Zulip, copying here:

> Eric Wittmann: The way that works is we put a message on the topic to create a new ID (one of the above). The storage then uses the in memory DB to do that. IDs must be the same across all replicas, regardless of when the replica starts up, so the "Create ID" messages can never be compacted. We're basically using these as counters.
>
> Eric Wittmann: But we also do it for artifact creation/update/delete. Because of the way our REST API allows users to treat an artifact as either a single thing that can be created/updated/deleted or as a container for a sequence of versions (with separate operations on each version), we need a UUID on the ArtifactKey because without it Kafka would compact away some required messages. For example:
> 
>     Create artifact A1
>     Update artifact A1 with V2
>     Update artifact A1 with V3
>
> If those messages didn' thave UUIDs, then Kafka would compact them leaving only (3) above, which would result in incorrect state.
> 
> Eric Wittmann: The right way to use this pattern is to send the full state for the object (e.g. an artifact) each time it changes. That way the correct state can be represented with only the most recent message. But that's not really a viable approach for our data model.

So none of those operations are compactable.  Some additional operations you could do that **are** compactable:

* Enable/configure artifact rules
* Edit artifact version metadata
* Set artifact owner
* Etc...

These are all compactable because every message of that type contains the full current state of that thing.  So as long as the **last** message is available, the state will be correct.  Wherever that is not the case (like creating a new version of an artifact) the message either has to be unique (hence the UUIDs) or has to contain **all versions** of the artifact.

> Note that the key for each message is unique.
> 
> And, whenever we do a delete operation, it creates 5 entries in the topic:
> 
> ```
> Key:
> {"tenantId":"_","artifactId":"8d620ce0-bd2b-4f7c-917e-65b7f7832764","uuid":"507e565c-adb5-493d-bb65-76edcbf8078b"}
> 
> Value:
> {"action":3}
> 
> Key:
> {"tenantId":"_","artifactId":"8d620ce0-bd2b-4f7c-917e-65b7f7832764","ruleType":"INTEGRITY"}
> 
> Value
> null
> 
> Key
> {"tenantId":"_","artifactId":"8d620ce0-bd2b-4f7c-917e-65b7f7832764","ruleType":"COMPATIBILITY"}
> 
> Value:
> null
> 
> Key
> {"tenantId":"_","artifactId":"8d620ce0-bd2b-4f7c-917e-65b7f7832764","ruleType":"VALIDITY"}
> 
> Value:
> null
> 
> Key
> {"tenantId":"_","artifactId":"8d620ce0-bd2b-4f7c-917e-65b7f7832764","version":"1"}
> 
> Value:
> null
> ```
> 
> Note that 4 of the 5 messages are tombstone (value is null), and still all of the keys are unique (they are not even equal to the ones from the creation/update operations).

What this is trying to do is add tombstone messages where it is **possible** to do so.  That includes the three rules that **may** have been configured for the artifact (they weren't, but the cleanup code doesn't know that) and it includes any metadata configuration that may have occurred for version 1 (again, you didn't modify the metadata for version 1, but the cleanup code doesn't know that).

Nothing else is **possible** to clenup for reasons mentioned above.

> 
> So, all the messages have unique keys and there's nothing to Kafka to really compact or delete.
> 
> I've noticed that those 9 records on the topic equal to ~23kb (some of them store the whole schema definition). meaning that those 75M messages we have on the topic in the load test env match the 24gb storage we see.

If you used a small number of unique schemas I would expect that it would re-use the content, so you wouldn't see millions of content messages.  But I could be wrong about that expectation or you could have been creating unique schema content for each artifact you created.

**Comment by carlesarnal** [comment]
Closing as Eric gave a good answer on this one. If there are still doubts please, re-open.
