### ISSUE TITLE
Make apicurio-registry work properly with Visual Studio Code

### ISSUE THREAD

**Issue by forsberg** [Apicurio/apicurio-registry#3821]
### Feature or Problem Description

Trying to open apicurio-registry in Visual Studio Code, most things work, but the generated code is not found, meaning that code navigation, linting etc suffers badly.

I realize the core developers probably use IntelliJ, but for me, not having to switch editor would help when trying to understand how something works, or when trying to fix a bug.

### Proposed Solution

This seems to be a known problem with the vscode-java extension, but there are workarounds. I'm sure that for an experienced java developer, applying fixes from https://github.com/redhat-developer/vscode-java/issues/566 or https://github.com/redhat-developer/vscode-java/issues/177 would be a simple thing. Not so much for me, way too deep into Maven rabbit hole land.

https://github.com/redhat-developer/vscode-java/issues/177#issuecomment-673333479 might indicate that some magic file needs to be added to https://github.com/Apicurio/apicurio-codegen

### Additional Context

Please? :)

**Comment by andreaTP** [comment]
Hi @forsberg !

A quick check: `apicurio-studio` -> you mean Registry right?

Most of us use `IntelliJ` as a primary IDE for Java projects, that's correct, but some are using Eclipse as well.
I'm personally known to be exceptionally bad with IDEs 😓 and, not having people using/checking constantly the VS Code integration might break from time to time.
I think we would happily merge PRs fixing this aspect, but, it would be on the community to support the maintenance IMHO.

That said, maybe, someone great at IDEs + Java like @fbricon is interested in looking into this.

**Comment by forsberg** [comment]
I can confirm that #3855 seems to fix the problem. Compliments to the fearless @jsenko, who obviously is not afraid of GINORMOUS XML files (like I am).

**Comment by andreaTP** [comment]
@fbricon @snjeza I keep facing similar issues with those and other Maven Plugins for generating code, the most recent being with @Javatar81 and this Maven Plugin: https://github.com/fabric8io/kubernetes-client/blob/main/doc/java-generation-from-CRD.md

The workaround of adding the `build-helper-maven-plugin` always works, but I think it's not the expected behavior as it works ootb in other IDEs (e.g. IntelliJ ).
Is this issue already reported somewhere?
Do you have a ticket I can follow to provide more context and track its resolution?

Thanks a lot in advance! 🙏
