### ISSUE TITLE
Validate the Artifact ID

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#455]
We should add validation of the Artifact ID in both the UI and the back-end.  We should reject IDs with characters we don't support.

Alternatively we can support all Artifact IDs as long as we test that we can support them in the API and the UI.

**Comment by EricWittmann** [comment]
@jsenko @carlesarnal @alesj Thoughts on this?  Should we constrain the artifact ID the user can provide?  For example reject it if the artifact ID contains spaces or other characters that URLs don't like?  Or do we just assume that the artifact ID can be URL encoded properly for use in the API?

**Comment by jsenko** [comment]
One argument for less restrictive names would be that if content extractors can extract artifact name from schemas instead of generating a new one, the name would have to either be transformed, or it can't be more restrictive than the related fields in the schemas. On the other hand, it would be a problem if the artifact name has to be in the URL. We would have to do a transformation anyway, or we can start using numeric IDs.

**Comment by carlesarnal** [comment]
The approach I like the most would be probably a costly one (from an impl POV). Having a less restrictive one for the `artifact_id` and another different one for API usage (`public_id`) which can be whatever we want, numerical, UUID etc. Something like the classical db internal id and the `public_id` or `code`.

**Comment by EricWittmann** [comment]
I wonder if there are storage-specific concerns around the artifact ID.  I don't think there should be anything like that for in-memory or SQL.... so probably not.

**Comment by EricWittmann** [comment]
I'm marking this as invalid because I was able to update the UI to support basically any characters you want in Artifact Ids.
