### ISSUE TITLE
apicurio/apicurio-registry-mem:latest mapping source code version

### ISSUE THREAD

**Issue by Rookiefreshman** [Apicurio/apicurio-registry#4959]
Important:
**question**: I want to know the source code version corresponding to this image and the API documentation for the version.
**question**:  How to find the corrent tag version by the docker hub?  whenI used the docker command to pull the docker images.
the docker command: docker pull apicurio/apicurio-registry-mem.
and then i used the command (eq:docker run -it -p 8080:8080 apicurio-registry-mem) to run the Apicurio service.It can run passed.
![image](https://github.com/user-attachments/assets/d88b647b-6550-4805-81aa-05200d7b7c1a)
its version number is 1.3.1.Final. is this accurately corresponding to the tag on Github? Also, I downloaded the source code for that version and encountered an error when running 'maven clean install'. the error detail content is "unable to find valid certification path to requested target！”
**question**： if you help answer the previous question,I would like to know the API documentation and best parctices for this version.For example ,i want to know the overall best practices for adding a schema and updating the version number and verification in registry-ui.Could you provide details on this?
this is a photo of the Registry-ui service.
![image](https://github.com/user-attachments/assets/c7023a1b-2a4e-4bef-b942-e8ef5e863ae6)

this is my envirorment:
  Docker Server Version: 26.1.3
   Security Options:
    seccomp
     Profile: builtin
   Kernel Version: 5.10.134-16.1.al8.x86_64
   Operating System: Alibaba Cloud Linux 3 (Soaring Falcon)
   OSType: linux

**Comment by carlesarnal** [comment]
Hello @Rookiefreshman 

First of all a quick note. For Apicurio Registry 2.x, we don't use latest, you must use either `latest-release`, `latest-snapshot`, or the concrete tag you want to use (e.g. 2.5.11.Final). We're currently in the process of releasing Apicurio Registry 3 and one of the differences is that there are no longer separate images for the different storage variants (I recommend checking `[this](https://github.com/Apicurio/apicurio-registry?tab=readme-ov-file#build-configuration)`). You're getting a very old version because of this, so I recommend addressing it first.

As for the correspondence between the tag and the code, if you use a concrete tag like the one I described it's easy, there's always a corresponding tag in GH for that release, for example, for 2.5.11.Final, [here's](https://github.com/Apicurio/apicurio-registry/releases/tag/2.5.11.Final) the corresponding tag.

Finally, about best practices and documentation, if you go to the [docs](https://www.apicur.io/registry/docs/apicurio-registry/2.6.x/index.html) page, there's a dropdown at the top-right that allows you to choose between the different versions.

I hope everything is clarified, if not, let me know.

**Comment by Rookiefreshman** [comment]
This site can’t be reachedgithub.com took too long to respond.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
[Running Windows Network Diagnostics](javascript:diagnoseErrors())
ERR_TIMED_OUT

**Comment by Rookiefreshman** [comment]
Thank you very much for your prompt reply.
I have some other questions to ask.
If I want to compile the source code corresponding to the 2.5.11.Final package in IntelliJ IDEA
using Maven.
Do i need to modify the configuration file in Maven?
for example as modify the Setting.xml to add the corresponding certificates or private repository addresses,
and ultimately package it into an SDK?

**Comment by carlesarnal** [comment]
> Rookiefreshman

You have all the instructions you need to build the project in the [README](https://github.com/Apicurio/apicurio-registry?tab=readme-ov-file#build-configuration) with instructions for both building *and* running Apicurio Registry. There's no need to setup any private repository or certificates.

**Comment by Rookiefreshman** [comment]
@carlesarnal I'm sorry for the misunderstanding. What I meant is that I want to run this as a Spring Boot service instead of packaging it with Docker. That's why I was asking whether there is a way to package the source code into an SDK within the project.

**Comment by carlesarnal** [comment]
> @carlesarnal I'm sorry for the misunderstanding. What I meant is that I want to run this as a Spring Boot service instead of packaging it with Docker. That's why I was asking whether there is a way to package the source code into an SDK within the project.

Hello @Rookiefreshman, 

Apicurio Registry is a Quarkus application. That's a framework that has lots of similarities with Spring Boot. You can run it in very much the same way you would run a Spring Boot app. We choose to do it in Docker just for convenience. Any other packaging (apart from docker, or using just plain java) is undocumented, so you would need to try it on your own.
