### ISSUE TITLE
Do you have a single example repo that does not require me to your work for you to make it work?

### ISSUE THREAD

**Issue by balayanv** [Apicurio/apicurio-registry#5262]
It is absurd to me that people put out giant repositories like this and you have to do your own debugging to make it work...

Why doesnt your repo compile? if you are using lombok you need to enable annotation processor in your pom file... why isnt it in the code? how do you even work with this without it...

Why are most of your images either not existing or require authentication...

**Comment by balayanv** [comment]
If you are providing a bunch of examples for these products put your docker compose files next to them with updated dependencies to images, dependencies that are public not your private docker images that work "on your machine"... its just common sense

**Comment by EricWittmann** [comment]
Hey man are you okay? I often struggle to decide how to respond to an issue like this. On the one hand, I of course have an immediate negative reaction and my instinct is to respond in kind. On the other hand, maybe you had a bad day. Maybe your dog just died. Maybe you are Dutch. I don't know. I hope everything is okay with you. Honestly.

Looking past the tone of your comment, I think there is a mix of reasonable and unreasonable content. 

Regarding compilation. I think you're going to need to give us some more information about what doesn't work. I compile this repository multiple times per day. It compiles in our CI workflows. My manager recently cloned the repository and it worked okay for him. I've tried building it from inside docker images and that goes okay. I'm sure there are reasons why it might not build. There is definitely plenty of complexity. Maybe give us a little more information and we can help? 

Regarding lombok. I would love it if you could explain more about annotation processors and our pom file. I did not know that such a thing was required. I don't see anything on the lombok website about that.

https://projectlombok.org/setup/maven

Does the lombok project need to update its Maven documentation?

Regarding the container images. I think you got us on this one. But authentication is, I think, just a red herring. What's actually going on is we are in the process of releasing a new major version. And we are making a big push to update the documentation. I think you may have caught things at just the wrong time. The documentation was stale and have some references to container images that no longer exist. And for whatever reason, it looks like QuayIO may respond with a 403 error for images that do not exist. I haven't actually dug deeply into this to make sure that when I'm telling you is true. Mostly because I know that the quick start documented on the website works just fine. Those container images exist, not just in QuayIO but also on docker hub. It's also not particularly difficult to find docker images on either of those platforms. And authentication is certainly not required. 

I think the feedback about docker compose is reasonable. The new 3.0 version of registry does require two container images if you want to also use the UI. And it would certainly be convenient to have a compose for that. It wasn't necessary in previous versions because the UI and back end were bundled into a single container image. 

I'm hopeful that most of your experience with registry is simply a matter of bad timing. The project website is, I think, clear and helpful. But until today (yes literally today) it was aligned with version 2.6. The code for that version is not on the main branch but rather on a 2.6.x branch. We have been working on getting a new major version out for a while now. So there has been a disconnect between the main branch and the project website and documentation. Today we released 3.0.0 with an updated website and updated documentation. 

Even though this is a free open source project, we are always looking for ways to improve community engagement and ease of use. And so we appreciate feedback. I will admit we appreciate it more when presented differently than this was. 🤣

**Comment by balayanv** [comment]
Was a bit mad when i wrote that (sorry about that didnt realise its free+opensource), but yeah points are IMO valid.

I had to add lombok annotation processing otherwise a bunch of getters and setters would not be generated and maven build would fail. Compiled using java 17 and latest maven. 

Then i spent 3 hours straight trying to get simple avro+kafka+registry to work, and it still had issues.

```
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.6.0</version>
            <configuration>
                <source>1.8</source>
                <target>1.8</target>
                <annotationProcessorPaths>
                    <path>
                        <groupId>org.projectlombok</groupId>
                        <artifactId>lombok</artifactId>
                        <version>1.16.12</version>
                    </path>                         
                </annotationProcessorPaths>
            </configuration>
        </plugin>
    </plugins>
</build>
```

Normally it will compile for people if they are doing it with IDEA but you say it compiles in CI CD so i have no idea how that magic happens, but for as long as i remember lombok you had to enable annotation processing for the compiler to do the job. Java needs those lombok generated methods at compile time, how would that happen without preprocessing... no idea

**Comment by EricWittmann** [comment]
Perhaps there's a difference in default config for JDK vendors?  It seems OpenJDK has automatic annotation processing enabled by default, but are considering disabling it by default in future releases.  I think this is relevant:

https://bugs.openjdk.org/browse/JDK-8306819

That said, I don't see any harm in adding lombok to the list of annotation processors in `pom.xml`.  We'll go ahead and do that.

As for getting a simple example working, we definitely have some work to do on improving our docs and readmes.  I was able to get the `simple-avro` example working OK, by doing this:

1. Run apicurio-registry:  
    `docker run -it -p 8080:8080 apicurio/apicurio-registry:3.0.0` (copied from the project site's Getting Started page)
2. Run Kafka:
    `docker compose  -f examples/tools/kafka-compose/kafka-compose.yaml up` (found in the README.md in the examples directory, needs updating)
3. Run the example:
    `mvn exec:java -Dexec.mainClass="io.apicurio.registry.examples.simple.avro.SimpleAvroExample"` (not documented, assumed knowledge of `mvn exec:java` - needs updating)

Ease of use, documentation, etc should all continue to improve now that we got 3.0.0 "out the door".

**Comment by andreaTP** [comment]
@balayanv would you be able to provide a reproducer in a container or CI where we can look for differences?

A sample GH Action should be relatively quick to build and would give us a common ground to bisect the issues you are experiencing.

> OpenJDK has automatic annotation processing enabled by default

Confirm, just having the annotation package on the classpath at compile time triggers the processor to run and is the "installation method" mentioned in [the lombok site](https://projectlombok.org/setup/maven).

**Comment by balayanv** [comment]
Annotation processor is not a problem, as the error message is self explanatory and its trivial to figure out and fix.

Whats much more annoying is to run the examples. Even though Eric's comment above worked fine, it is the registry in memory version... (in my case i was having issues making kafka store version work). 

Even with the simple in memory version one would assume changing the image to kafka version would start using kafka, but all sorts of connectivity issues start from there. Error messages are not helpful so you end up poking this and that trying to figure out whats causing the issue.

Imo these examples each should be 1 compose file each. I'd suggest to build all the examples into one docker image and just make sure that a parameter controls which example gets launched.

That would be deterministic, work on any platform consistently without issues.

**Comment by andreaTP** [comment]
Thanks for your input @balayanv , we all agree that there is always margin for improvement.

I would welcome and support contributions improving the current status, PRs are welcome :slightly_smiling_face:
