### ISSUE TITLE
Support for MySQL storage

### ISSUE THREAD

**Issue by Yoni-Weisberg** [Apicurio/apicurio-registry#5309]
### Feature or Problem Description

Implementing MySQL as an SQL storage option

### Proposed Solution

I can create the necessary classes, but I’ll need your assistance, particularly with testing.

### Additional Context

I noticed that this has already been suggested [here](https://github.com/Apicurio/apicurio-registry/issues/1546), but there hasn't been any progress on it.

**Comment by EricWittmann** [comment]
This will be great. And it would not be very difficult.  Happy to help! 

If you want, we can start with a dedicated branch for the work. I don't think we need any new tests. We just need to run existing tests against the MySQL database.

**Comment by Yoni-Weisberg** [comment]
Hi @EricWittmann, I think I am done, please let me know the process of creating new branch, so I can push my changes.

**Comment by EricWittmann** [comment]
Hey @Yoni-Weisberg that's great!  You should be able to just open a Pull Request against the `main` branch.  The project README should have information about that.

Also, we very recently re-enabled the SQL test.  So that should actually help you a lot I think.  You should be able to create a new variant of that test very easily.  Use this for inspiration:

https://github.com/Apicurio/apicurio-registry/blob/main/app/src/test/java/io/apicurio/registry/storage/impl/sql/PostgresqlStorageTest.java

**Comment by Yoni-Weisberg** [comment]
Hi @EricWittmann, I've opened a PR: https://github.com/Apicurio/apicurio-registry/pull/5411

**Comment by EricWittmann** [comment]
PR merged, thanks @Yoni-Weisberg 

Closing.
