### ISSUE TITLE
Support generic JDBC properties

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#5513]
We have a set of explicit properties for JDBC here https://github.com/Apicurio/apicurio-registry/blob/main/app/src/main/java/io/apicurio/registry/storage/impl/sql/RegistryDatasourceProducer.java#L62 . 

Instead of adding properties one-by-one in the future, we should consider a more general approach to configure JDBC, similar to what we do for Kafka here https://github.com/Apicurio/apicurio-registry/blob/main/app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlFactory.java#L85 .

Related to #5507

**Comment by carlesarnal** [comment]
We've introduced this kind of support due to the Quarkus inability to deactivate a particular datasource. That has been addressed in Quarkus, so we must go back and use the standard Quarkus properties (keeping the Registry specific ones we've already defined for compatibiltiy). That gives us back the flexibility for the jdbc configuration.

**Comment by jsenko** [comment]
So the changes in the linked PR are not necessary? I see the property [quarkus.datasource.jdbc.max-lifetime](https://quarkus.io/guides/datasource#quarkus-agroal_quarkus-datasource-jdbc-max-lifetime) is available.

**Comment by carlesarnal** [comment]
> So the changes in the linked PR are not necessary? I see the property [quarkus.datasource.jdbc.max-lifetime](https://quarkus.io/guides/datasource#quarkus-agroal_quarkus-datasource-jdbc-max-lifetime) is available.

It's very possible, I'm trying to finish the Quarkus upgrade and that was going to be my next thing, but we must avoid adding any new properties that already exist in Quarkus.

**Comment by carlesarnal** [comment]
This is now possible on main and will be possible in `3.0.4.` Four datasources have been defined, one per each db schema type. In order to configure additional values, the Quarkus standard way can be used. For example, for configuring the maximum lifetime for the mysql datasource, the environment variable `QUARKUS_DATASOURCE_MYSQL_JDBC_MAX_LIFETIME`. Same goes for postgresq, mssql, or h2, the same pattern applies.
