### ISSUE TITLE
docs: incorrect path in rest api docs

### ISSUE THREAD

**Issue by famartinrh** [Apicurio/apicurio-registry#691]
https://access.redhat.com/webassets/avalon/d/Red_Hat_Integration-2020-Q2-Getting_Started_with_Service_Registry-en-US/files/registry-rest-api.htm

All paths should start with `/api`

**Comment by smccarthy-ie** [comment]
@famartinrh This should be assessed by a developer and fixed in the following file if needed: https://github.com/Apicurio/apicurio-registry/blob/1.2.x/common/src/main/resources/META-INF/openapi.json 

One possible quick fix is to add the following text to the description at the start of the `.json` file:

**Note**: The Apicurio Registry REST API is available from `http://MY-REGISTRY-URL/api`. You must ensure that all API operation paths include `/api`, for example, `api/ids/{globalId}`.

Alternatively, we could update all of the examples individually if needed.

**Comment by EricWittmann** [comment]
I'm not in favor of updating the OpenAPI file to include `/api` in each of the endpoints.  However, the OpenAPI spec does support a "servers" section for this purpose:  https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#serverObject

We can use that feature for this if we want.

**Comment by EricWittmann** [comment]
To be clear - I think the way to leverage this feature is to modify the OpenAPI file (at runtime) that we return when users hit the `/api` url in the Registry.  We could dynamically add a "servers" section with a server configured to reflect the appropriate root path.

**Comment by EricWittmann** [comment]
@smccarthy-ie when you get back could you add some language to the .json file (based on your suggestion) that mentions the `/api` context path?  Perhaps mentioning that `/api` is the **default** location of the API.  There is no guarantee that any particular deployment of the registry will have that context path (though it is very likely).

**Comment by smccarthy-ie** [comment]
@EricWittmann @famartinrh I updated the `openapi.json` file with a **Note** about this a while ago:

See https://access.redhat.com/webassets/avalon/d/Red_Hat_Integration-2020-Q2-Getting_Started_with_Service_Registry-en-US/files/registry-rest-api.htm

I've also updated the source now in Apicurio Studio with Eric's clarification that `/api` is only the default: 

**Note**: The Apicurio Registry REST API is available from `http://MY-REGISTRY-URL/api` by default. Therefore you must prefix all API operation paths with `/api` in this case. For example: `api/ids/{globalId}`.

I think it's OK to close this issue now, unless you want to modify the `openapi.json` file further. WDYT?

**Comment by EricWittmann** [comment]
lgtm

**Comment by famartinrh** [comment]
thanks @smccarthy-ie
