### ISSUE TITLE
Spring Integration

### ISSUE THREAD

**Issue by tomasAlabes** [Apicurio/apicurio-registry#699]
Hi, I'm trying to replace Confluent's registry for apicurio in a Spring-Kafka app, and after some fight, exploration and trials I almost got it working (an example and doc for it would be great). 
At the moment the consumers are not getting the events and I see a lot of these messages: 
```
CDI container is not available
```
I had to add `javax.enterprise:cdi-api:1.2` as a dependency because of a `ClassNotFound`, but I assume it should be using the Spring CDI, but I don't know how.
For now I'm just using `/api/ccompat` with the same Confluent SerDes.
I'm using the `REGISTRY_USE_SPECIFIC_AVRO_READER_CONFIG_PARAM` set to `true`.

Is the CDI configurable to use Spring?

Thanks

**Comment by katheris** [comment]
Hi @tomasAlabes, I'm running into similar issues to you, but with just a plain Java app. I got it working in my IDE by adding `org.jboss.resteasy:resteasy-core:4.5.5.Final` and `org.jboss.resteasy:resteasy-client:4.5.5.Final` along with the cdi one you added. Still trying to get it working in my runnable jar though.

I hope that helps you get a bit further.

**Comment by tomasAlabes** [comment]
Thanks @katheris, I was able to make it work after debugging for a while. 

There's a bug in the code when trying to use the `REGISTRY_USE_SPECIFIC_AVRO_READER_CONFIG_PARAM` property. Just setting it to `true` is not enough, you also have to set the `REGISTRY_AVRO_DATUM_PROVIDER_CONFIG_PARAM` prop to `DefaultAvroDatumProvider`, so that the other one is picked up.

In your case you might need to use some cdi implementation along with the `cdi-api`, maybe is picked up from the classpath.

**Comment by EricWittmann** [comment]
I'm honestly not sure that CDI is actually required when using the client.  I think the `CDI container is not available` is informational rather than an error.  I could easily be wrong on that.  @alesj might have some thoughts.

I know we've covered this, but it's worth pointing out that we're going to be replacing the current client with something that has fewer dependencies.  You can see a PR for that work here:  https://github.com/Apicurio/apicurio-registry/compare/master...carlesarnal:replace-generated-client-672

We need to have a discussion about whether to simply create a drop-in replacement for the current client or whether to deprecate the existing one and provide a new one with a better interface (e.g. remove all the CompletionStage return values).  But either way it should make **everything** much better.

**Comment by EricWittmann** [comment]
Once that client is available, we can start looking at improvements to the serdes layer to make things easier to consume.  And I also agree that we need better documentation and examples in this area.

**Comment by tomasAlabes** [comment]
Thanks for the info @EricWittmann, looking forward to the new client.

Also please have in mind the bug I mentioned in my previous comment:

> There's a bug in the code when trying to use the REGISTRY_USE_SPECIFIC_AVRO_READER_CONFIG_PARAM property. Just setting it to true is not enough, you also have to set the REGISTRY_AVRO_DATUM_PROVIDER_CONFIG_PARAM prop to DefaultAvroDatumProvider, so that the other one is picked up.

**Comment by EricWittmann** [comment]
@tomasAlabes OK thanks - could you open a separate ticket for that?  I'll tag it as Documentation and assign appropriately.

**Comment by EricWittmann** [comment]
@tomasAlabes Hey - the `master` branch includes the new client I mentioned which should help out a lot with the dependency issues.  We should be doing a 1.3.0.Final release this week if you want to wait for that.

**Comment by tomasAlabes** [comment]
Closing after 1.3.0 where the extra dependencies are not needed. Also the specific reader bug is fixed in 1.3.1.
