### ISSUE TITLE
Transitioning from `DEPRECATED` state?

### ISSUE THREAD

**Issue by ajborley** [Apicurio/apicurio-registry#722]
Apicurio restricts the transitions between states via the ArtifactStateExt class (1) but it seems that once an artifact is in `DEPRECATED` state it can only then transition to `DELETED` state. Typically, a deprecated resource is still usable, but will eventually become unusable, which I think maps to the `DISABLED` state in Apicurio. 
Additionally, if a user accidentally deprecates an artifact, there is no way to reverse that action at the moment, beyond creating a new artifact.

Is there an expected lifecycle of an artifact version? My guess is something like the following:

`ENABLED` -> `DEPRECATED` -> `DISABLED` -> `DELETED` 

With transitions permitted between any of `ENABLED`, `DEPRECATED` and `DISABLED`, but not from `DELETED`, which is a final irreversible state.

(1) https://github.com/Apicurio/apicurio-registry/blob/fe1282fa084038362fb8be13b5580d5be9afc639/app/src/main/java/io/apicurio/registry/storage/ArtifactStateExt.java#L39-L43

**Comment by EricWittmann** [comment]
This is an interesting question, actually.  I can see the reasoning behind the current approach.  You can go from `DEPRECATED` only to `DELETED` if we assume that "Un-Deprecating" is not a thing that should be allowed.  So in that case you can only go to `DELETED` as the next step because going into `DISABLED` state allows you to then go back to `ENABLED`.

In one sense I think the artifact version "state" is actually combining two concepts:

* Enabled/Disabled
* Deprecated

But I think what we've done is a reasonable simplification/combination of those concepts.  The question becomes what state transitions should be allowed.

I think perhaps we have erred on the side of being too restrictive with our state transitions.  As you say, accidentally deprecating something allows for no going back.  I think I would argue that we should allow more transitions and trust users to create their own processes to properly utilize the states.

So that was all a long way of saying - yes let's allow `DEPRECATED` to `ENABLED` and also `DEPRECATED` to `DISABLED`.

@alesj @carlesarnal @jsenko thoughts?

**Comment by carlesarnal** [comment]
I agree, but, once we have authentication/authorization I would suggest restricting this kind of transitions (especially the `DEPRECATED` to `ENABLED` one) to concrete roles.

**Comment by EricWittmann** [comment]
That's a good idea.  We should start a document around Registry roles and what those roles have permission to do.

**Comment by EricWittmann** [comment]
Fixed by PR https://github.com/Apicurio/apicurio-registry/pull/783
