### ISSUE TITLE
Ensure logging can be enabled for new registry client

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#760]
We need to make sure that the new registry client can have logging enabled.  Things like HTTP request/response headers and whatnot should be optionally logged.  Let's introduce some sort of ENV variable or system property or something that can turn it on/off.  This may be very important for debugging e.g. kafka applications.

**Comment by carlesarnal** [comment]
Hey @EricWittmann, I think it's a good idea to add some defaults but, since we're using `OkHttp`, maybe we can rely on its `
`Interceptors` to allow the users to tweak the logs to whatever they want. I've added an example [here](https://github.com/carlesarnal/apicurio-registry-client-demo/blob/master/src/main/java/io/apicurio/registry/client/demo/HeadersLoggingDemo.java) on how to log request/response headers.

**Comment by carlesarnal** [comment]
@EricWittmann, thougts on this?

**Comment by EricWittmann** [comment]
Yeah I think leaning on the OK HTTP interceptors is fine.  But let's create an example in the new `apicurio-registry-examples` repository that shows how custom logging via interceptor would work.

**Comment by carlesarnal** [comment]
Ok, I'll move the existing example [here](https://github.com/carlesarnal/apicurio-registry-client-demo/blob/master/src/main/java/io/apicurio/registry/client/demo/HeadersLoggingDemo.java) into that repository.

**Comment by carlesarnal** [comment]
[Example](https://github.com/Apicurio/apicurio-registry-examples/pull/2) added to the repo, I'm closing this.
