### ISSUE TITLE
Docs: Link to registry-rule-types doesn't work

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#871]
This might be the case for any link that goes from one "guide" to another, but so far I've only noticed it for `registry-rule-types`.  Example:  on this page:

https://www.apicur.io/registry/docs/apicurio-registry/getting-started/assembly-intro-to-registry-rules.html#registry-rules-work

There is the following link at the bottom:

![image](https://user-images.githubusercontent.com/1890703/94040584-22906980-fd97-11ea-9fbc-9d9fd7fde3bd.png)

The link has an href of:

`https://www.apicur.io/registry/docs/apicurio-registry/getting-started/assembly-intro-to-registry-rules.html#registry-rule-types`

But that doesn't work.  It should be this:

`https://www.apicur.io/registry/docs/apicurio-registry/getting-started/assembly-registry-reference.html#registry-rule-types`

**Comment by smccarthy-ie** [comment]
Hey @EricWittmann, @cfoskin 

I think this is because the playbook used to automate the doc build is missing the required attributes to make the cross-reference links work: 
https://github.com/Apicurio/apicurio-docs-playbook/blob/master/registry-docs-playbook.yml

These attribute links have already been added in the playbook used for local testing: 
https://github.com/Apicurio/apicurio-registry/blob/master/docs/local-test-playbook.yml

So the fix should be to keep both playbooks in sync. Thanks.

**Comment by smccarthy-ie** [comment]
BTW, the links to the "Apicurio Registry REST API documentation" are also broken, giving 404s. For example, on https://www.apicur.io/registry/docs/apicurio-registry/getting-started/assembly-intro-to-the-registry.html 

In this case, the fix is to ensure that the automated doc build picks up the `registry-rest-api.htm` file from 
https://github.com/Apicurio/apicurio-registry/tree/master/docs/modules/ROOT/assets/attachments
and puts it in
https://www.apicur.io/registry/docs/apicurio-registry/_attachments/registry-rest-api.htm

**Comment by smccarthy-ie** [comment]
Hi @EricWittmann, 
When I build now locally using https://github.com/Apicurio/apicurio-docs-playbook, all the broken links are fixed :) Thanks!

So it looks like the latest fixed doc build just needs to be pushed to the website now?  I'm keen to resolve this one now that IBM are also looking at our new docs website :)

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio.github.io/commit/b84b9897b22accb662cfc079339adb6ba85d55a0
